<?php
$pageId = Mage::getSingleton('cms/page')->getId();

$arrLinkAnalysisPages = array('7', '8', '9');
$arrWebsiteAuditPages = array();
$arrLinkSmallSeoTools = array();

$$arrEmailmarketing = array();
$arrFeedback = array();
$arrKeywordManager = array('58');
$arrQuiz = array();
$arrCodebazzar = array();
$arrInfluencer = array();
$arrServicemanagement = array();

$pageBuilder = array('10', '11', '20');
$videoCreator = array('21');
$directory = array('22');
$ssm = array('23');
$bloggers = array('24');

$activeClass = '';

$moduleName = Mage::app()->getRequest()->getModuleName();   //smallseotools
?>
<style>
    .active_left_menu{
        color: #007bff;
        background-color: #20222e;
        font-weight: 600;
    }
</style>
<div class="side-menu-fixed">
    <div class="scrollbar side-menu-bg">
        <ul class="nav navbar-nav side-menu" id="sidebarnav">
            <li class="mt-10 mb-10 text-muted pl-4 font-medium menu-title">Module List </li>
            <li>
                <a class="<?php echo(in_array($pageId, $arrLinkAnalysisPages) || $moduleName == 'linkanalysis' ? 'active_left_menu' : ''); ?>" href="javascript:document.location.href='<?php echo Mage::getBaseUrl(); ?>linkanalysis'">
                    <i class="ti-menu-alt"></i>
                    <span class="right-nav-text">Link Analysis</span> 
                </a>
            </li>
            <!-- ----------------- Website Audit ------------------->
            <li>
                <a class="<?php echo(in_array($pageId, $arrWebsiteAuditPages) || $moduleName == 'websiteaudit' ? 'active_left_menu' : ''); ?>" href="javascript:document.location.href='<?php echo Mage::getBaseUrl(); ?>websiteaudit'">
                    <i class="ti-menu-alt"></i>
                    <span class="right-nav-text">Website Audit</span> 
                </a>
            </li>
            <!-- ----------------- Website Audit ------------------->
            <!-- menu item chat-->
            <?php /* ?><li> 
              <a class="<?php echo(in_array($pageId, $pageBuilder) || $moduleName == 'pagebuilder' ? 'active_left_menu' : ''); ?>" href="<?php echo $this->getUrl('page-builder');?>">
              <i class="ti-book"></i>
              <span class="right-nav-text">Page Builder </span>
              </a>
              </li><?php */ ?>

            <!-- --------------- Page Builder Starts ------------------>
            <!--<li>
                <a href="javascript:void(0);" data-toggle="collapse" data-target="#elements" class="">
                    <div class="pull-left"><i class="ti-book"></i><span class="right-nav-text">Page Builder</span></div>
                    <div class="pull-right"><i class="ti-plus"></i></div><div class="clearfix"></div>
                </a>
                <ul id="elements" class="collapse" data-parent="#sidebarnav">
                    <li><a href="javascript:document.location.href='<?php echo Mage::getBaseUrl(); ?>page'" class="<?php echo ($pageId == 10 ? 'active_left_menu' : ''); ?>">Page</a></li>
                    <li><a href="alerts.html">Analytics</a></li>
                    <li><a href="button.html">Integrations</a></li>
                    <li><a href="colorpicker.html">Domains</a></li>
                    <li><a href="dropdown.html">Team Members</a></li>
                </ul>
            </li>-->
            <!-- --------------- Page Builder Ends -------------------->

            <li>
                <a class="<?php echo(in_array($pageId, $videoCreator) || $moduleName == 'pagebuilder' ? 'active_left_menu' : ''); ?>" href="<?php echo $this->getUrl('video-creator'); ?>">
                    <i class="ti-video-camera"></i>
                    <span class="right-nav-text">Video Creator</span> 
                    <!--<span class="badge badge-pill badge-danger float-right mt-1">59</span>--> 
                </a>
            </li>

            <li>
                <a href="<?php echo $this->getUrl('smallseotools'); ?>" class="<?php echo(in_array($pageId, $arrLinkSmallSeoTools) || $moduleName == 'smallseotools' ? 'active_left_menu' : ''); ?>">
                    <i class="ti-email"></i>
                    <span class="right-nav-text">Small SEO Tools</span> 
                    <!--<span class="badge badge-pill badge-warning float-right mt-1">HOT</span>--> 
                </a>
            </li>

            <!-- menu item mailbox-->
            <li>
                <a href="<?php echo $this->getUrl('emailmarketing'); ?>" class="<?php echo(in_array($pageId, $arrEmailmarketing) || $moduleName == 'emailmarketing' ? 'active_left_menu' : ''); ?>">
                    <i class="ti-email"></i>
                    <span class="right-nav-text">Email Marketing</span> 
                    <!--<span class="badge badge-pill badge-warning float-right mt-1">HOT</span>--> 
                </a>
            </li>
            <?php /* ?><li>
              <a class="<?php echo(in_array($pageId, $directory) || $moduleName == 'pagebuilder' ? 'active_left_menu' : ''); ?>" href="<?php echo $this->getUrl('directory');?>">
              <i class="ti-bag"></i>
              <span class="right-nav-text">Directory</span>
              <!--<span class="badge badge-pill badge-warning float-right mt-1">HOT</span>-->
              </a>
              </li>
              <li>
              <a class="<?php echo(in_array($pageId, $ssm) || $moduleName == 'sma' ? 'active_left_menu' : ''); ?>" href="<?php echo $this->getUrl('sma');?>">
              <i class="ti-clip"></i>
              <span class="right-nav-text">Social Media Audit</span>
              <!--<span class="badge badge-pill badge-warning float-right mt-1">HOT</span>-->
              </a>
              </li><?php */ ?>
            <!--------------------------------------------------------->
            <li>
                <a href="javascript:void(0);" data-toggle="collapse" data-target="#elements" class="<?php echo(in_array($pageId, $ssm) || $moduleName == 'sma' ? 'active_left_menu' : ''); ?>">
                    <div class="pull-left"><i class="ti-book"></i><span class="right-nav-text">Social Media Audit</span></div>
                    <div class="pull-right"><i class="ti-plus"></i></div><div class="clearfix"></div>
                </a>
                <ul id="elements" class="collapse" data-parent="#sidebarnav">
                    <li><a href="<?php echo $this->getUrl('sma'); ?>">Dashboard</a></li>
                    <li><a href="javascript:document.location.href='<?php echo Mage::getBaseUrl(); ?>top-instagram'" class="<?php echo ($pageId == 52 ? 'active_left_menu' : ''); ?>">Top Instagram</a></li>
                    <li><a href="javascript:document.location.href='<?php echo Mage::getBaseUrl(); ?>top-twitter'" class="<?php echo ($pageId == 53 ? 'active_left_menu' : ''); ?>">Top Twitter</a></li>
                    <li><a href="javascript:document.location.href='<?php echo Mage::getBaseUrl(); ?>top-twitch'" class="<?php echo ($pageId == 54 ? 'active_left_menu' : ''); ?>">Top Twitch</a></li>
                    <li><a href="javascript:document.location.href='<?php echo Mage::getBaseUrl(); ?>top-youtube'" class="<?php echo ($pageId == 55 ? 'active_left_menu' : ''); ?>">Top Youtube</a></li>
                    <li><a href="javascript:document.location.href='<?php echo Mage::getBaseUrl(); ?>top-tubblr'" class="<?php echo ($pageId == 55 ? 'active_left_menu' : ''); ?>">Top Tumblr</a></li>
                </ul>
            </li>
            <!-- ------------------------------------------------------->

            <?php /* ?><li>
              <a href="<?php echo $this->getUrl('influencer');?>" class="<?php echo(in_array($pageId, $arrInfluencer) || $moduleName == 'influencer' ? 'active_left_menu' : ''); ?>">
              <i class="ti-book"></i>
              <span class="right-nav-text">Social Media Mngmt</span>
              </a>
              </li><?php */ ?>
            <!-- ------------- Social Media Management Starts ---------------->
            <li>
                <a href="javascript:void(0);" data-toggle="collapse" data-target="#elementsSMM" class="">
                    <div class="pull-left"><i class="ti-book"></i><span class="right-nav-text">Social Media Mngmt</span></div>
                    <div class="pull-right"><i class="ti-plus"></i></div><div class="clearfix"></div>
                </a>
                <ul id="elementsSMM" class="collapse" data-parent="#sidebarnav">
                    <li><a href="<?php echo $this->getUrl('influencer'); ?>"><i class="fa fa-cubes" style="font-size:14px; margin-right: 5px;"></i>Dashboard</a></li>
                    <li><a href="<?php echo $this->getUrl('account_manager'); ?>"><i class="fa fa-user-o" style="font-size:14px; margin-right: 5px;"></i>Account Manager</a></li>  
                    <li><a href="<?php echo $this->getUrl('smm-post-instagram'); ?>"><i class="fa fa-edit" style="font-size:14px; margin-right: 5px;"></i>Post</a></li>
                    <li><a href="<?php echo $this->getUrl('schedule'); ?>"><i class="fa fa-hourglass-half" style="font-size:14px; margin-right: 5px;"></i>Schedules</a></li>
                    <li><a href="<?php echo $this->getUrl('bulk-posting'); ?>"><i class="fa fa-hourglass-half" style="font-size:14px; margin-right: 5px;"></i>Bulk Posting</a></li>
                    <li><a href="<?php echo $this->getUrl('captions'); ?>"><i class="fa fa-share-square-o" style="font-size:14px; margin-right: 5px;"></i>Captions</a></li>
                    <li><a href="<?php echo $this->getUrl('file_manager'); ?>"><i class="fa fa-folder-o active_option" style="font-size:14px; margin-right: 5px;"></i>File Manager</a></li>
                    <li><a href="<?php echo $this->getUrl('smm_tools'); ?>"><i class="fa fa-wrench" style="font-size:14px; margin-right: 5px;"></i>Tools</a></li>
                    <li><a href="<?php echo $this->getUrl('publish_all'); ?>"><i class="fa fa-laptop" style="font-size:14px; margin-right: 5px;"></i>Publish All</a></li>
                </ul>
            </li>
            <!-- ------------- Social Media Management Ends ------------------>

            <?php /* ?><li>
              <a class="<?php echo(in_array($pageId, $bloggers) || $moduleName == 'pagebuilder' ? 'active_left_menu' : ''); ?>" href="<?php echo $this->getUrl('bloggers');?>">
              <i class="ti-email"></i>
              <span class="right-nav-text">W. L. Blogger's</span>
              <!--<span class="badge badge-pill badge-warning float-right mt-1">HOT</span>-->
              </a>
              </li>
              <li>
              <a class="<?php echo(in_array($pageId, $arrFeedback) || $moduleName == 'feedback' ? 'active_left_menu' : ''); ?>" href="<?php echo $this->getUrl('feedback');?>">
              <i class="ti-email"></i>
              <span class="right-nav-text">Feedback</span>
              <!--<span class="badge badge-pill badge-warning float-right mt-1">HOT</span>-->
              </a>
              </li><?php */ ?>
            <li>
                <a class="<?php echo(in_array($pageId, $arrKeywordManager) || $moduleName == 'keywordmanager' ? 'active_left_menu' : ''); ?>" href="<?php echo $this->getUrl('keywordmanager'); ?>">
                    <i class="ti-email"></i>
                    <span class="right-nav-text">Keyword Manager</span> 
                    <!--<span class="badge badge-pill badge-warning float-right mt-1">HOT</span>--> 
                </a>
            </li>
            <?php /* ?><li>
              <a class="<?php echo(in_array($pageId, $arrQuiz) || $moduleName == 'quiz' ? 'active_left_menu' : ''); ?>" href="<?php echo $this->getUrl('quiz');?>">
              <i class="ti-email"></i>
              <span class="right-nav-text">Quiz</span>
              <!--<span class="badge badge-pill badge-warning float-right mt-1">HOT</span>-->
              </a>
              </li>
              <li>
              <a class="<?php echo(in_array($pageId, $arrCodebazzar) || $moduleName == 'codebazzar' ? 'active_left_menu' : ''); ?>" href="<?php echo $this->getUrl('codebazzar');?>">
              <i class="ti-email"></i>
              <span class="right-nav-text">Code Bazzar</span>
              <!--<span class="badge badge-pill badge-warning float-right mt-1">HOT</span>-->
              </a>
              </li>
              <li>
              <a class="<?php echo(in_array($pageId, $arrServicemanagement) || $moduleName == 'servicemanagement' ? 'active_left_menu' : ''); ?>" href="<?php echo $this->getUrl('servicemanagement');?>">
              <i class="ti-email"></i>
              <span class="right-nav-text">Service Management</span>
              <!--<span class="badge badge-pill badge-warning float-right mt-1">HOT</span>-->
              </a>
              </li>
              <li>
              <a href="javascript:void(0);">
              <i class="ti-email"></i>
              <span class="right-nav-text">Affiliation &amp; Labels</span>
              <!--<span class="badge badge-pill badge-warning float-right mt-1">HOT</span>-->
              </a>
              </li>

              <li>
              <a href="javascript:void(0);">
              <i class="ti-email"></i>
              <span class="right-nav-text">Website Analytics</span>
              <!--<span class="badge badge-pill badge-warning float-right mt-1">HOT</span>-->
              </a>
              </li>
              <li>
              <a href="javascript:void(0);">
              <i class="ti-email"></i>
              <span class="right-nav-text">Wallet</span>
              <!--<span class="badge badge-pill badge-warning float-right mt-1">HOT</span>-->
              </a>
              </li>
              <li>
              <a href="javascript:void(0);">
              <i class="ti-email"></i>
              <span class="right-nav-text">Settings</span>
              <!--<span class="badge badge-pill badge-warning float-right mt-1">HOT</span>-->
              </a>
              </li><?php */ ?>
            <li>
                <a href="<?php echo Mage::getBaseUrl(); ?>my-profile">
                    <i class="ti-email"></i>
                    <span class="right-nav-text">My Profile</span> 
                    <!--<span class="badge badge-pill badge-warning float-right mt-1">HOT</span>--> 
                </a>
            </li>
            <?php /* ?><li>
              <a href="javascript:void(0);">
              <i class="ti-email"></i>
              <span class="right-nav-text">Plan &amp; Pricing</span>
              <!--<span class="badge badge-pill badge-warning float-right mt-1">HOT</span>-->
              </a>
              </li><?php */ ?>
        </ul>
    </div> 
</div> 

<style>
    .active_option{
        color: #fff !important;
        border: none !important;
        font-size: 14px;
        text-align: center;
        cursor: text;
        font-weight: 600;
    }
</style>