<script src="js/jquery-3.3.1.min.js"></script>
<script src="js/plugins-jquery.js"></script>
<script>var plugin_path = 'js/';</script>
<script src="js/chart-init.js"></script>
<script src="js/calendar.init.js"></script>
<script src="js/sparkline.init.js"></script>
<script src="js/morris.init.js"></script>
<script src="js/datepicker.js"></script>
<script src="js/sweetalert2.js"></script>
<script src="js/toastr.js"></script>
<script src="js/validation.js"></script>
<script src="js/lobilist.js"></script>
<script src="js/custom.js"></script>