<?php
if (Mage::getSingleton('customer/session')->isLoggedIn()) {
    $customerData = Mage::getSingleton('customer/session')->getCustomer();
    $customerId = $customerData->getId();
} else {
    
}

$fbUserCollection = Mage::getModel('influencerusers/influencerusers')
        ->getCollection()
        ->addFieldToFilter('status', '1')
        ->addFieldToFilter('customer_id', $customerId)
        ->addFieldToFilter('platform', '1');

$igUserCollection = Mage::getModel('influencerusers/influencerusers')
        ->getCollection()
        ->addFieldToFilter('status', '1')
        ->addFieldToFilter('customer_id', $customerId)
        ->addFieldToFilter('platform', '2');

$twUserCollection = Mage::getModel('influencerusers/influencerusers')
        ->getCollection()
        ->addFieldToFilter('status', '1')
        ->addFieldToFilter('customer_id', $customerId)
        ->addFieldToFilter('platform', '3');

$helper = Mage::helper('influencerusers/data');
$instagramCredentialsArr = $helper->getIntagramCredentials();

//echo "<pre>"; print_r($igUserCollection->getData()); die();
?>

<div class="page-title">
    <div class="row">
        <div class="col-sm-6">
            <h4 class="mb-0"> SMM - Account Manager</h4>
        </div>
        <div class="col-sm-6">
            <ol class="breadcrumb pt-0 pr-0 float-left float-sm-right">
                <li class="breadcrumb-item"><a href="<?php echo Mage::getBaseUrl(); ?>" class="default-color">Home</a></li>
                <li class="breadcrumb-item active">Account Manager</li>
            </ol>
        </div>
    </div>
</div>

<?php //echo file_get_contents(Mage::getBaseUrl() . "options?active_option=accountManager"); ?>
<!-- --------------- Modal Start ------------------>
<input type="button" data-toggle="modal" data-target=".bd-example-modal-lg" id="btnModal" style="display: none;">
<div class="modal fade bd-example-modal-lg" tabindex="-1" role="dialog" aria-hidden="true">
    <div class="modal-dialog modal-lg">
        <div class="modal-content">
            <div class="modal-header" style="padding-bottom: 0px;">
                <div class="modal-title">
                    <div class="mb-30" style="padding-bottom: 0px; margin-bottom: 0px;">
                        <h6 id="titleModal">EXPERTISE</h6>
                    </div>
                </div>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body" id="modal_body">
                <div class="row">
                    <div class="col-md-6 col-sm-6" style="border-right: solid 4px #ccc;">
                        <form class="form-inline">
                            <div class="input-group mb-2 mr-sm-2">
                                <div class="input-group-prepend">
                                    <div class="input-group-text">
                                        <i class="fa fa-user-o" style="font-size:20px;"></i>
                                    </div>
                                </div>
                                <input type="text" class="form-control" id="instaUname" placeholder="Instagram Username" required="required">
                            </div>
                            <div class="input-group mb-2 mr-sm-2">
                                <div class="input-group-prepend">
                                    <div class="input-group-text">
                                        <i class="fa fa-key" style="font-size:20px;"></i>
                                    </div>
                                </div>
                                <input type="password" class="form-control" id="instaPwd" placeholder="Instagram Password" required="required">
                                <div class="invalid-feedback" style="font-weight: 600; display: block;" id="erreMsgDiv"></div>
                            </div>
                            <div class="input-group mb-2 mr-sm-2">
                                <div class="custom-control custom-checkbox my-1 mr-sm-2">
                                    <input onclick="showHidePassword();" type="checkbox" class="custom-control-input" id="customControlInline">
                                    <label class="custom-control-label" for="customControlInline">Show Password</label>
                                </div>
                            </div>
                            <div class="input-group-prepend input-group mb-2 mr-sm-2" style="text-align: center; width: 90%;">
                                <button onclick="loginToInstagram()" style="width: 100%;" type="button" class="btn btn-primary mb-2">Login</button>
                            </div>
                            <input type="submit" id="frmInstaLoginBtn" style="display: none;">
                        </form>
                    </div>
                    <div class="col-md-6 col-sm-6" style="text-align: center;">
                        <label>Click instagram logo to use instagram plarform</label>
                        <hr>
                        <a href="https://api.instagram.com/oauth/authorize/?client_id=<?php echo $instagramCredentialsArr['INSTAGRAM_CLIENT_ID']; ?>&redirect_uri=<?php echo urlencode($instagramCredentialsArr['INSTAGRAM_REDIRECT_URI']); ?>&response_type=code&scope=basic"><img style="width: 10em; border: solid 4px #ccc; padding: 10px; border-radius: 8px;" src="https://www.socicos.com/skin/frontend/seo/default/images/instalogo.png"></a>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button id="btnModelClose" type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
<!-- --------------- Modal Ends ------------------->
<div class="row" id="users">
    <!-- -------------- New Layout Of Account Manager Starts ---------------->
    <div class="col-xl-12 mb-30">
        <div class="card card-statistics h-100">
            <div class="card-body">
                <div class="tab nav-border" style="position: relative;">
                    <div class="d-block d-md-flex justify-content-between">
                        <div class="d-block w-100">
                            <img style="width: 10em;" src="<?php echo $this->getSkinUrl('images/instalogo.png', array('_secure' => true)); ?>">
                        </div>
                        <div class="d-block d-md-flex nav-tabs-custom">
                            <ul class="nav nav-tabs" id="myTab" role="tablist">
                                <li class="nav-item">
                                    <a style="padding: 5px;" class="nav-link active show" id="months-tab" data-toggle="tab" href="#months" role="tab" aria-controls="months" aria-selected="true">
                                        <i class="fa fa-instagram" style="font-size:15px; font-weight: 600; padding-left: 2px;"></i>
                                        <lable style="font-size: 15px; padding-right: 3px; font-weight: 600;">Instagram</lable>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a style="padding: 5px;" class="nav-link" id="year-tab" data-toggle="tab" href="#year" role="tab" aria-controls="year" aria-selected="false">
                                        <i class="fa fa-facebook-f" style="font-size:15px; font-weight: 600; padding-left: 2px;"></i>
                                        <lable style="font-size: 15px; padding-right: 3px; font-weight: 600;">Facebook</lable>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a id="addUserLink" style="padding: 5px 5px;" data-html="true" data-container="body" data-toggle="popover" data-placement="bottom" data-content="<p class='popoverlink'><a href='javascript:launchInstagramAddUserPanel();'>Instagram</a></p><p class='popoverlink'><a href='#'>Facebook</a></p>" href="javascript:void(0)" class="btn btn-outline-warning btn-sm">
                                        <i class="fa fa-user-plus" style="font-size:21px; color: green;"></i>
                                    </a>
                                </li>
                            </ul>

                        </div>
                    </div>
                    <hr>
                    <div class="tab-content" id="myTabContent">
                        <div class="tab-pane fade active show" id="months" role="tabpanel" aria-labelledby="months-tab">
                            <?php if ($igUserCollection->getSize() > 0): ?>
                                <?php foreach ($igUserCollection as $igUser): ?>
                                    <div class="row">
                                        <div class="col-md-2 col-sm-6">
                                            <img id="img<?php echo $igUser->getId(); ?>" style="width: 5em; border: solid 2px #666; padding: 2px; border-radius: 1em;" class="img-fluid" src="<?php echo $igUser->getProfilePicture(); ?>" alt="">
                                        </div>
                                        <div class="col-md-4 col-sm-6">
                                            <h6 class="mb-0 sm-mt-5"><?php echo $igUser->getName(); ?></h6>
                                            <p class="sm-mb-5 d-block">
                                                <label class="badge badge-success"><?php echo $igUser->getUsername(); ?></label>
                                                <?php if (strlen($igUser->getPassword()) <= 1): ?>
                                                    <br><label class="badge badge-danger">Enter Password to Activate</label>
                                                    <a id="link<?php echo $igUser->getId(); ?>" data-html="true" data-container="body" data-toggle="popover" data-placement="bottom" data-content='<div class="form-group"><label for="password<?php echo $igUser->getId(); ?>">Password</label><br><input style="width:60%; float:left; padding: 8px 10px 7px 10px; margin-bottom:7px;" type="password" class="form-control" id="password<?php echo $igUser->getId(); ?>" placeholder="Password"><button onclick="savePassword(<?php echo $igUser->getId(); ?>)" style="width:38%; float:right; padding-left:0px;" type="submit" class="btn btn-primary"><i id="btnIcon<?php echo $igUser->getId(); ?>" class="fa fa-floppy-o" style="font-size:17px; margin-right:10px;"></i>Save</button></div>' style="border-radius: 5px;" href="javascript:void(0);" class="btn btn-outline-warning btn-sm">
                                                        <i class="fa fa-key" style="font-size:15px; font-weight: 600;"></i>
                                                    </a>
                                                <?php endif; ?>
                                            </p> 
                                            <span class="mb-0">Added On: <b class="text-success"> <?php echo $igUser->getCreatedTime(); ?></b> </span>
                                        </div>
                                        <div class="col-md-2 col-sm-6 col-6 sm-mt-20" style="text-align: center;">
                                            <h5 class="text-dark mb-0"><b><?php echo $igUser->getFollowers(); ?></b></h5>
                                            <span>Followers</span>
                                        </div>
                                        <div class="col-md-2 col-sm-6 col-6 sm-mt-20" style="text-align: center;">
                                            <h5 class="text-success mb-0"><b><?php echo $igUser->getFollowing(); ?></b></h5>
                                            <span>Following</span>
                                        </div>
                                        <div class="col-md-1 col-sm-6 col-6 sm-mt-20" style="text-align: center;">
                                            <!--<a data-html="true" data-container="body" data-toggle="popover" data-placement="bottom" data-content='<div class="form-group">
                                               <label for="exampleInputPassword1">Password</label><br>
                                            <input style="width:60%; float:left; padding: 8px 10px 7px 10px; margin-bottom:7px;" type="password" class="form-control" id="exampleInputPassword1" placeholder="Password"><button style="width:38%; float:right;" type="submit" class="btn btn-primary">Save</button>
                                        </div>' style="border-radius: 5px;" href="javascript:void(0);" class="btn btn-outline-warning btn-sm">
                                                <i class="fa fa-key" style="font-size:17px;"></i>
                                            </a>-->
                                        </div>
                                        <div class="col-md-1 col-sm-6 col-6 sm-mt-20" style="text-align: center;">
                                            <a style="border-radius: 5px;" href="javascript:deleteUser('<?php echo $igUser->getId(); ?>');" class="btn btn-outline-warning btn-sm">
                                                <i class="fa fa-trash-o" style="font-size:17px;"></i>
                                            </a>
                                        </div>
                                    </div>
                                    <hr>
                                <?php endforeach; ?>
                            <?php else: ?>

                            <?php endif; ?>
                        </div> 
                        <div class="tab-pane fade" id="year" role="tabpanel" aria-labelledby="year-tab">
                            <div class="row mb-30">
                                <div class="col-md-2 col-sm-6">
                                    <img class="img-fluid" src="images/blog/09.jpg" alt="">
                                </div>
                                <div class="col-md-6 col-sm-6">
                                    <h6 class="mb-0 sm-mt-5">Walk out 10 years into</h6>
                                    <p class="sm-mb-5 d-block">Understanding the price and having the willingness to pay. </p> 
                                    <span class="mb-0">by - <b class="text-danger">TheZayka</b> </span>
                                </div>
                                <div class="col-md-2 col-sm-6 col-6 sm-mt-20">
                                    <h5 class="text-dark mb-0"><b>12,549</b></h5>
                                    <span>Sales</span>
                                </div>
                                <div class="col-md-2 col-sm-6 col-6 sm-mt-20">
                                    <h5 class="theme-color mb-0"><b>$1,656</b></h5>
                                    <span>Revenue</span>
                                </div>
                            </div>
                            <div class="row mb-30">
                                <div class="col-md-2 col-sm-6">
                                    <img class="img-fluid" src="images/blog/06.jpg" alt="">
                                </div>
                                <div class="col-md-6 col-sm-6">
                                    <h6 class="mb-0 sm-mt-5">Step out on to the path</h6>
                                    <p class="sm-mb-5 d-block">Success to you and then pull it out when you are.</p> 
                                    <span class="mb-0">by - <b class="text-info">CarDealer</b> </span>
                                </div>
                                <div class="col-md-2 col-sm-6 col-6 sm-mt-20">
                                    <h5 class="text-primary mb-0"><b>1,366</b></h5>
                                    <span>Sales</span>
                                </div>
                                <div class="col-md-2 col-sm-6 col-6 sm-mt-20">
                                    <h5 class="text-secondary mb-0"><b>$4,536</b></h5>
                                    <span>Revenue</span>
                                </div>
                            </div>
                            <div class="row mb-30">
                                <div class="col-md-2 col-sm-6">
                                    <img class="img-fluid" src="images/blog/07.jpg" alt="">
                                </div>
                                <div class="col-md-6 col-sm-6">
                                    <h6 class="mb-0 sm-mt-5">Briefly imagine that you</h6>
                                    <p class="sm-mb-5 d-block">Motivators for your personality and your personal goals. </p> 
                                    <span class="mb-0">by - <b class="text-success">SamMartin</b> </span>
                                </div>
                                <div class="col-md-2 col-sm-6 col-6 sm-mt-20">
                                    <h5 class="text-success mb-0"><b>465</b></h5>
                                    <span>Sales</span>
                                </div>
                                <div class="col-md-2 col-sm-6 col-6 sm-mt-20">
                                    <h5 class="text-danger mb-0"><b>$499</b></h5>
                                    <span>Revenue</span>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-md-2 col-sm-6">
                                    <img class="img-fluid" src="images/blog/08.jpg" alt="">
                                </div>
                                <div class="col-md-6 col-sm-6">
                                    <h6 class="mb-0 sm-mt-5">You continue doing what</h6>
                                    <p class="sm-mb-5 d-block">The first thing to remember about success is that. </p> 
                                    <span class="mb-0">by - <b class="text-warning">Cosntro</b> </span>
                                </div>
                                <div class="col-md-2 col-sm-6 col-6 sm-mt-20">
                                    <h5 class="text-warning mb-0"><b>4,456</b></h5>
                                    <span>Sales</span>
                                </div>
                                <div class="col-md-2 col-sm-6 col-6 sm-mt-20">
                                    <h5 class="text-info mb-0"><b>$6,485</b></h5>
                                    <span>Revenue</span>
                                </div>
                            </div>
                        </div>
                    </div> 
                </div>
            </div>
        </div>
    </div>
    <!-- -------------- New Layout Of Account Manager Ends ------------------>
</div>

<script>

    var username = "";
    var password = "";
    var userId = "";
    
    function showHidePassword() {
        var checkboxObj = document.getElementById("customControlInline");
        if (checkboxObj.checked) {
            document.getElementById("instaPwd").setAttribute("type", "text");
        } else {
            document.getElementById("instaPwd").setAttribute("type", "password");
        }
    }

    function launchInstagramAddUserPanel() {
        document.getElementById("titleModal").innerHTML = "Add Instagram User";
        document.getElementById("addUserLink").click();
        document.getElementById("btnModal").click();
    }

    function loginToInstagram() {
        username = document.getElementById("instaUname").value;
        var password = document.getElementById("instaPwd").value;
        var customerId = "<?php echo $customerId; ?>";
        if ((username == '' || username == null) || (password == '' || password == null)) {
            document.getElementById("frmInstaLoginBtn").click();
        } else {
            jQuery("#pre-loader").css("opacity", '0.8');
            jQuery("#pre-loader").show();
            var url = "<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB, true); ?>lib/ssm/instagram/examples/doLogin.php";
            jQuery.ajax({
                type: "POST",
                url: url,
                data: {userId: userId, password: password, username: username, customerId: customerId},
                success: function (data)
                {
                    var objData = jQuery.parseJSON(data);
                    if (parseInt(objData.status) == 1) {
                        document.location.href = "https://www.socicos.com/index.php/account_manager";
                    }else{
                        var msg = objData.msg;
                        document.getElementById("erreMsgDiv").innerHTML = msg;
                    }
                    //var $result = jQuery(data).find('#myTabContent').html();
                    jQuery("#pre-loader").hide();
                }
            });
        }
    }

    function savePassword(userId) {
        var customerId = "<?php echo $customerId; ?>";
        password = document.getElementById("password" + userId).value;
        var image = document.getElementById("img" + userId).src;
        var url = "<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB, true); ?>lib/ssm/instagram/examples/doLogin.php";
        if (password == "" || password == null) {
            swal({
                title: "Account Verify",
                text: "Please enter Instagram password to verify the account",
                imageUrl: image
            });
        } else {
            jQuery("#btnIcon" + userId).removeClass("fa fa-floppy-o").addClass("fa fa-spinner fa-spin");
            jQuery.ajax({
                type: "POST",
                url: url,
                //data: {userId: userId, password: password},
                data: {userId: userId, password: password, username: username, customerId:customerId},
                success: function (data)
                {
                    var objData = jQuery.parseJSON(data);
                    if (parseInt(objData.status) == 1) {
                        document.location.href = "<?php echo Mage::getBaseUrl(); ?>account_manager";
                    }
                    //var $result = jQuery(data).find('#myTabContent').html();

                }
            });
        }
    }

    function addEditUsersForInstagram() {
        var url = 'https://api.instagram.com/oauth/authorize/?client_id=<?php echo $instagramCredentialsArr['INSTAGRAM_CLIENT_ID']; ?>&redirect_uri=<?php echo urlencode($instagramCredentialsArr['INSTAGRAM_REDIRECT_URI']); ?>&response_type=code&scope=basic';
        //window.open(url);
        //var content = "<?php //echo @file_get_contents("https://api.instagram.com/oauth/authorize/?client_id=".$instagramCredentialsArr['INSTAGRAM_CLIENT_ID'] . "&redirect_uri=" . urlencode($instagramCredentialsArr['INSTAGRAM_REDIRECT_URI']) . "&response_type=code&scope=basic");         ?>";
        document.location.href = url;
    }

    function deleteUser(userId) {
        var url = "<?php echo Mage::getBaseUrl(); ?>influencerusers/index/deleteUser?userId=" + userId;
        jQuery("#pre-loader").css("opacity", '0.8');
        jQuery("#pre-loader").show();
        jQuery.ajax({
            type: "POST",
            url: url,
            data: ""/*form.serialize()*/,
            success: function (data)
            {
                var objData = jQuery.parseJSON(data);
                //----------------------------------
                jQuery.ajax({
                    type: "POST",
                    url: objData.url,
                    data: ""/*form.serialize()*/,
                    success: function (data)
                    {
                        var $result = jQuery(data).find('#myTabContent').html();
                        jQuery("#myTabContent").html($result);
                        jQuery("#pre-loader").hide();
                    }
                });
                //----------------------------------
            }
        });
    }

    function addEditUsers(userType) {
        //alert(userType);
        var url = "<?php echo Mage::getBaseUrl(); ?>add_edit_user?userType=" + userType;
        jQuery("#pre-loader").css("opacity", '0.8');
        jQuery("#pre-loader").show();
        jQuery.ajax({
            type: "POST",
            url: url,
            data: ""/*form.serialize()*/,
            success: function (data)
            {
                jQuery("#titleModal").html("Create Facebook User");
                jQuery("#pre-loader").hide();
                jQuery("#modal_body").html(data);
                document.getElementById("btnModal").click();
            }
        });
    }
</script>

<style>
    .popoverlink{
        margin-bottom: 3px;
    }

    .popoverlink:hover{
        /*background: #ccc;*/
    }
</style>