<div class="page-title">
    <div class="row">
        <div class="col-sm-6">
            <h4 class="mb-0"> Welcome to Social Media Management</h4>
        </div>
        <div class="col-sm-6">
            <ol class="breadcrumb pt-0 pr-0 float-left float-sm-right">
                <li class="breadcrumb-item"><a href="<?php echo Mage::getBaseUrl(); ?>" class="default-color">Home</a></li>
                <li class="breadcrumb-item active">Social Media Management</li>
            </ol>
        </div>
    </div>
</div>

<?php //echo file_get_contents(Mage::getBaseUrl() . "options?active_option=home"); ?>

<div class="row">
    <div class="col-12 mb-30 ">
        <div class="card card-statistics h-100">
            <div class="card-body">
                <div class="row">
                    <div class="col-xl-8">
                        <h5 class="card-title"> Social Media Post Summary</h5>
                        <div class="tab round">
                            <ul class="nav nav-tabs" role="tablist">
                                <li class="nav-item">
                                    <a class="nav-link active show" id="home-07-tab" data-toggle="tab" href="#home-07" role="tab" aria-controls="home-07" aria-selected="true"> <i class="fa fa-home"></i> Facebook</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" id="profile-07-tab" data-toggle="tab" href="#profile-07" role="tab" aria-controls="profile-07" aria-selected="false"><i class="fa fa-user"></i> Instagram </a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" id="portfolio-07-tab" data-toggle="tab" href="#portfolio-07" role="tab" aria-controls="portfolio-07" aria-selected="false"><i class="fa fa-picture-o"></i> Twitter </a>
                                </li>
                                <!--<li class="nav-item">
                                    <a class="nav-link" id="contact-07-tab" data-toggle="tab" href="#contact-07" role="tab" aria-controls="contact-07" aria-selected="false"><i class="fa fa-check-square-o"></i> Contact </a>
                                </li>-->
                            </ul>
                            <div class="tab-content">
                                <div class="tab-pane fade active show" id="home-07" role="tabpanel" aria-labelledby="home-07-tab">
                                    <p>Facebook Post Summary </p>
                                </div>
                                <div class="tab-pane fade" id="profile-07" role="tabpanel" aria-labelledby="profile-07-tab">
                                    <p>Instagram Post Summary </p>
                                </div>
                                <div class="tab-pane fade" id="portfolio-07" role="tabpanel" aria-labelledby="portfolio-07-tab">
                                    <p>Twitter Post Summary</p>
                                </div>
                                <!--<div class="tab-pane fade" id="contact-07" role="tabpanel" aria-labelledby="contact-07-tab">
                                    <p>The other virtues practice in succession by Franklin were silence, order, resolution, frugality, industry, sincerity, Justice, moderation, cleanliness, tranquility, chastity and humility. For the summary order he followed a little scheme of employing his time each day. From five to seven each morning he spent in bodily personal attention, saying a short prayer, thinking over the day’s business and resolutions.</p>
                                </div>-->
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-4 mt-4 mt-xl-0">
                        <div class="claerfix">
                            <h5 class="card-title">Post Content Summary</h5>
                        </div>
                        <div class="row">
                            <div class="col-lg-7">
                                <div id="morris-donut" style="height: 300px;"></div>
                            </div>
                            <div class="col-lg-5">
                                <h3>50,500 </h3>
                                <div class="row no-gutters">
                                    <div class="col-12 col-sm-4 col-md-4 col-lg-12 mt-30">
                                        <b>Media </b>
                                        <p class="text-success">4,564</p>
                                    </div>
                                    <div class="col-12 col-sm-4 col-md-4 col-lg-12 mt-30">
                                        <b>Text</b>
                                        <p class="text-info">1,616</p>
                                    </div>
                                    <div class="col-12 col-sm-4 col-md-4 col-lg-12 mt-30">
                                        <b>Links</b>
                                        <p class="text-danger">6,546</p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-xl-4 col-md-6 mb-30">
        <div class="card card-statistics h-100">
            <div class="card-body p-0">
                <div class="p-3 bg-white">
                    <div class="row">
                        <div class="col-sm-6 col-6 align-self-center">
                            <h5>Success</h5>
                            <span class="text-success">655 Share</span>
                        </div>
                        <div class="col-sm-6 col-6 align-self-center text-right">
                            <span class="round-chart mb-0" data-percent="84" data-size="80" data-color="#28a745"> <span class="percent"></span> </span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>  
    <div class="col-xl-4 col-md-6 mb-30">
        <div class="card card-statistics h-100">
            <div class="card-body p-0">
                <div class="p-3 bg-white">
                    <div class="row">
                        <div class="col-sm-6 col-6 align-self-center">
                            <h5>Failed</h5>
                            <span class="text-danger">252 Share</span>
                        </div>
                        <div class="col-sm-6 col-6 align-self-center text-right">
                            <span class="round-chart mb-0" data-percent="52" data-size="80" data-color="#dc3545"> <span class="percent"></span> </span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-xl-4 col-md-6 mb-30">
        <div class="card card-statistics h-100">
            <div class="card-body p-0">
                <div class="p-3 bg-white">
                    <div class="row">
                        <div class="col-sm-6 col-6 align-self-center">
                            <h5>Completed</h5>
                            <span class="text-warning">5260 total</span>
                        </div>
                        <div class="col-sm-6 col-6 align-self-center text-right">
                            <span class="round-chart mb-0" data-percent="55" data-size="80" data-color="#ffc107"> <span class="percent"></span> </span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>