<div class="page-title">
    <div class="row">
        <div class="col-sm-6">
            <h4 class="mb-0"> Social Media Management - Post</h4>
        </div>
        <div class="col-sm-6">
            <ol class="breadcrumb pt-0 pr-0 float-left float-sm-right">
                <li class="breadcrumb-item"><a href="<?php echo Mage::getBaseUrl(); ?>" class="default-color">Home</a></li>
                <li class="breadcrumb-item active">Post </li>
            </ol>
        </div>
    </div>
</div>

<?php //echo file_get_contents(Mage::getBaseUrl() . "options?active_option=post"); ?>

<div class="row">
    <div class="col-12 mb-30 ">
        <div class="card card-statistics h-100">
            <div class="card-body">
                <div class="row">
                    <div class="col-xl-12">
                        <h5 class="card-title"> Post</h5>
                        
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>