<?php $path = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB, true) . 'socicos/'; ?>
<!DOCTYPE html>
<html>
    <?php echo $this->getLayout()->createBlock('core/template')->setTemplate('catalog/product/head.phtml')->toHtml(); ?>
    <body>
        <header class="main-header header-style-five">

            <!-- Header Top -->
            <?php echo $this->getLayout()->createBlock('core/template')->setTemplate('catalog/product/header_top.phtml')->toHtml(); ?>
        </div>
        <!-- Header Top End -->

        <!-- Main Box -->
        <div class="main-box">
            <div class="auto-container">
                <div class="outer-container clearfix">
                    <!--Logo Box-->
                    <div class="logo-box">
                        <div class="logo"><a href="<?php echo Mage::getBaseUrl(); ?>"><img src="<?php echo $path; ?>images/logo-2.png" alt=""></a></div>
                    </div>

                    <!--Nav Outer-->
                    <div class="nav-outer clearfix">

                        <!-- Main Menu -->
                        <nav class="main-menu">
                            <div class="navbar-header">
                                <!-- Toggle Button -->
                                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                </button>
                            </div>

                            <div class="navbar-collapse collapse clearfix">
                                <?php echo $this->getLayout()->createBlock('core/template')->setTemplate('catalog/product/top_navigation1.phtml')->toHtml(); ?>
                            </div>
                        </nav>
                        <!-- Main Menu End-->
                    </div>
                    <!--Nav Outer End-->

                </div>
            </div>
        </div>

        <!--Sticky Header-->
        <div class="sticky-header">
            <div class="auto-container">

                <div class="outer-container clearfix">
                    <!--Logo Box-->
                    <?php echo $this->getLayout()->createBlock('core/template')->setTemplate('catalog/product/logo.phtml')->toHtml(); ?>
                    <!--Nav Outer-->
                    <div class="nav-outer clearfix">
                        <!-- Main Menu -->
                        <nav class="main-menu">
                            <div class="navbar-header">
                                <!-- Toggle Button -->
                                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                </button>
                            </div>

                            <div class="navbar-collapse collapse clearfix">
                                <?php echo $this->getLayout()->createBlock('core/template')->setTemplate('catalog/product/top_navigation2.phtml')->toHtml(); ?>
                            </div>
                        </nav>
                        <!-- Main Menu End-->

                    </div>
                    <!--Nav Outer End-->

                </div>

            </div>
        </div>
        <!--End Sticky Header-->

    </header>
    <!--End Main Header --><!--Page Title-->
    <section class="page-title" style="background-image:url(<?php echo $path; ?>images/background/pattern-4.png);">
        <div class="auto-container">
            <h1>About Company</h1>
        </div>
        <!--Page Info-->
        <div class="page-info">
            <div class="auto-container">
                <div class="inner-container">
                    <ul class="bread-crumb">
                        <li><a href="<?php echo Mage::getBaseUrl(); ?>">Home</a></li>
                        <li>About Company</li>
                    </ul>
                </div>
            </div>
        </div>
        <!--End Page Info-->
    </section>
    <!--End Page Title-->

    <!--We Are Section-->
    <section class="we-are-section">
        <div class="auto-container">
            <div class="row clearfix">
                <!--Content Column-->
                <div class="content-column col-md-6 col-sm-12 col-xs-12">
                    <div class="inner-column">
                        <h2>Who We are</h2>
                        <div class="bold-text">Provide automation tools for effective analytics and strategies in one click.</div>
                        <div class="text">
                            <p>We are a group of young entrepreneurs with experience in digital media marketing over 6+ years. We intent to provide marketing management solutions to our users. We are one stop solution for all your digital marketing automation and well known for in-depth internet marketing reports. We transform our user's vision to winning business solutions. We convey the correct marketing tool that constructs esteem, beats the competitor and produce a generous enduring monetary effect for our clients.</p>
                            <p>The prime objective of SOCICOS to render best world-class professional tools to our users while providing enterprise to focus on their core business..</p>
                        </div>
                        <a href="#" class="theme-btn btn-style-one">Meet Team</a>
                    </div>
                </div>
                <!--Carousel Column-->
                <div class="carousel-column col-md-6 col-sm-12 col-xs-12">
                    <div class="inner-column">

                        <div class="single-verticle-carousel">
                            <div class="slide">

                                <!--Monthy Block-->
                                <div class="monthy-block" style="margin-top: 15px;">
                                    <div class="inner-box">
                                        <div class="month">Mar 2016 <span class="dott"></span></div>
                                        <h3><a href="#">Formation of the company.</a></h3>
                                        <div class="text">Ognikasa Services Private Limited was registered. From the day one, we were all set to start and execute our plan.</div>
                                    </div>
                                </div>

                                <!--Monthy Block-->
                                <div class="monthy-block">
                                    <div class="inner-box">
                                        <div class="month">Jan 2017 <span class="dott"></span></div>
                                        <h3><a href="#">Multiple Plans & Multiple Executions!</a></h3>
                                        <div class="text">There were multiple marketing tools developing under one roof on a high priority basis for faster launch and better serving.</div>
                                    </div>
                                </div>

                            </div>

                            <div class="slide">

                                <!--Monthy Block-->
                                <div class="monthy-block" style="margin-top: 15px;">
                                    <div class="inner-box">
                                        <div class="month">Mar 2018 <span class="dott"></span></div>
                                        <h3><a href="#">Master The Brains Affiliated</a></h3>
                                        <div class="text">The company required more powerful brains to execute the product for real.</div>
                                    </div>
                                </div>

                                <!--Monthy Block-->
                                <div class="monthy-block">
                                    <div class="inner-box">
                                        <div class="month">Jun 2018 <span class="dott"></span></div>
                                        <h3><a href="#">The Launch Was Not Easy</a></h3>
                                        <div class="text">Yes, we finally launched our first SEO tool called SOCICOS ANALYZER v1. The response was very good and got a lot of feedback. Positive responses made Socicos stronger.</div>
                                    </div>
                                </div>

                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </section>
    <!--End We Are Section-->

    <!--Services Section Two-->
    <section class="services-section-two">
        <div class="auto-container">
            <!--Sec Title-->
            <div class="sec-title light centered">
                <h2>Why Choose Us</h2>
            </div>
            <div class="row clearfix">

                <!--Services Block Three-->
                <div class="services-section-three col-md-4 col-sm-6 col-xs-12">
                    <div class="inner-box">
                        <h3>6 Years Experience</h3>
                        <div class="title">In this Industry</div>
                        <div class="image">
                            <img src="<?php echo $path; ?>images/icons/services-4.png" alt="" />
                        </div>
                        <!--<a class="read-more" href="services.html"><span class="icon flaticon-right-arrow-1"></span> Read more</a>-->
                    </div>
                </div>

                <!--Services Block Three-->
                <div class="services-section-three col-md-4 col-sm-6 col-xs-12">
                    <div class="inner-box">
                        <h3>Experienced Talented</h3>
                        <div class="title">Employeers</div>
                        <div class="image">
                            <img src="<?php echo $path; ?>images/icons/services-5.png" alt="" />
                        </div>
                        <!--<a class="read-more" href="services.html"><span class="icon flaticon-right-arrow-1"></span> Read more</a>-->
                    </div>
                </div>

                <!--Services Block Three-->
                <div class="services-section-three col-md-4 col-sm-6 col-xs-12">
                    <div class="inner-box">
                        <h3>Certified & Proven</h3>
                        <div class="title">SEO Process</div>
                        <div class="image">
                            <img src="<?php echo $path; ?>images/icons/services-6.png" alt="" />
                        </div>
                        <!--<a class="read-more" href="services.html"><span class="icon flaticon-right-arrow-1"></span> Read more</a>-->
                    </div>
                </div>

            </div>
        </div>
    </section>
    <!--End Services Section Two-->

    <!--Marketing Section Two-->
    <section class="marketing-section-two" style="background-image:url(<?php echo $path; ?>images/background/3.png)">
        <div class="auto-container">
            <div class="steps-blocks">
                <div class="row clearfix">

                    <!--Step Block-->
                    <div class="step-block col-md-3 col-sm-6 col-xs-12">
                        <div class="inner-box">
                            <div class="icon-box">
                                <span class="icon"><img src="<?php echo $path; ?>images/icons/market-icon-1.png" alt="" /></span>
                            </div>
                            <h3>Enter Website URL</h3>
                            <div class="step-number">Stage 01</div>
                        </div>
                    </div>

                    <!--Step Block-->
                    <div class="step-block col-md-3 col-sm-6 col-xs-12">
                        <div class="inner-box">
                            <div class="icon-box">
                                <span class="icon"><img src="<?php echo $path; ?>images/icons/market-icon-2.png" alt="" /></span>
                            </div>
                            <h3>In depth Analysis</h3>
                            <div class="step-number">Stage 02</div>
                        </div>
                    </div>

                    <!--Step Block-->
                    <div class="step-block col-md-3 col-sm-6 col-xs-12">
                        <div class="inner-box">
                            <div class="icon-box">
                                <span class="icon"><img src="<?php echo $path; ?>images/icons/market-icon-3.png" alt="" /></span>
                            </div>
                            <h3>Find Solution</h3>
                            <div class="step-number">Stage 03</div>
                        </div>
                    </div>

                    <!--Step Block-->
                    <div class="step-block col-md-3 col-sm-6 col-xs-12">
                        <div class="inner-box">
                            <div class="icon-box">
                                <span class="icon"><img src="<?php echo $path; ?>images/icons/market-icon-4.png" alt="" /></span>
                            </div>
                            <h3>improvement strategy</h3>
                            <div class="step-number">Stage 04</div>
                        </div>
                    </div>

                </div>
            </div>
            <h3>We’ll Make Your Web Marketing! More Efficient!</h3>
            <a href="quote.html" class="theme-btn btn-style-one">Get Started</a>
        </div>
    </section>

    <!--Partners Section-->
    <?php echo $this->getLayout()->createBlock('core/template')->setTemplate('catalog/product/partners.phtml')->toHtml(); ?>
    <!--End Partners Section-->
</section>
<!--End Partners Section-->

<!--Main Footer-->
<?php echo $this->getLayout()->createBlock('core/template')->setTemplate('catalog/product/footer.phtml')->toHtml(); ?>
<!--Main Footer-->
<!--Bottom Parallax-->

</div>
<!--End pagewrapper-->

<!--Scroll to top-->
<div class="scroll-to-top scroll-to-target" data-target="html"><span class="icon fa fa-angle-double-up"></span></div>

<script src="<?php echo $path; ?>js/jquery.js"></script>
<!--Revolution Slider-->
<script src="<?php echo $path; ?>assets/revolution/js/jquery.themepunch.revolution.min.js"></script>
<script src="<?php echo $path; ?>assets/revolution/js/jquery.themepunch.tools.min.js"></script>
<script src="<?php echo $path; ?>assets/revolution/js/extensions/revolution.extension.actions.min.js"></script>
<script src="<?php echo $path; ?>assets/revolution/js/extensions/revolution.extension.carousel.min.js"></script>
<script src="<?php echo $path; ?>assets/revolution/js/extensions/revolution.extension.kenburn.min.js"></script>
<script src="<?php echo $path; ?>assets/revolution/js/extensions/revolution.extension.layeranimation.min.js"></script>
<script src="<?php echo $path; ?>assets/revolution/js/extensions/revolution.extension.migration.min.js"></script>
<script src="<?php echo $path; ?>assets/revolution/js/extensions/revolution.extension.navigation.min.js"></script>
<script src="<?php echo $path; ?>assets/revolution/js/extensions/revolution.extension.parallax.min.js"></script>
<script src="<?php echo $path; ?>assets/revolution/js/extensions/revolution.extension.slideanims.min.js"></script>
<script src="<?php echo $path; ?>assets/revolution/js/extensions/revolution.extension.video.min.js"></script>
<script src="<?php echo $path; ?>js/main-slider-script.js"></script>

<script src="<?php echo $path; ?>js/jquery.js"></script>
<script src="<?php echo $path; ?>js/bootstrap.min.js"></script>
<script src="<?php echo $path; ?>js/jquery.fancybox.pack.js"></script>
<script src="<?php echo $path; ?>js/jquery.fancybox-media.js"></script>
<script src="<?php echo $path; ?>js/owl.js"></script>
<script src="<?php echo $path; ?>js/wow.js"></script>
<script src="<?php echo $path; ?>js/validate.js"></script>
<script src="<?php echo $path; ?>js/jquery-ui.js"></script>
<script src="<?php echo $path; ?>js/knob.js"></script>
<script src="<?php echo $path; ?>js/slick.js"></script>
<script src="<?php echo $path; ?>js/appear.js"></script>
<script src="<?php echo $path; ?>js/script.js"></script>
<!--<script src="<?php echo $path; ?>js/validate.js"></script>-->
<script src="http://maps.google.com/maps/api/js?key=AIzaSyBKS14AnP3HCIVlUpPKtGp7CbYuMtcXE2o"></script>
<script src="<?php echo $path; ?>js/map-script.js"></script>

<!--Scroll to top-->
<div class="scroll-to-top scroll-to-target" data-target="html"><span class="icon fa fa-angle-double-up"></span></div>


</body>
</html>