<!DOCTYPE html>
<html>
<?php echo $this->getLayout()->createBlock('core/template')->setTemplate('catalog/product/head.phtml')->toHtml(); ?>
<body>
<header class="main-header header-style-five">

    <!-- Header Top -->
    <?php echo $this->getLayout()->createBlock('core/template')->setTemplate('catalog/product/header_top.phtml')->toHtml(); ?>
    </div>
    <!-- Header Top End -->

    <!-- Main Box -->
    <div class="main-box">
        <div class="auto-container">
            <div class="outer-container clearfix">
                <!--Logo Box-->
                <?php echo $this->getLayout()->createBlock('core/template')->setTemplate('catalog/product/logo.phtml')->toHtml(); ?>
                <!--Nav Outer-->
                <div class="nav-outer clearfix">

                    <!-- Main Menu -->
                    <nav class="main-menu">
                        <div class="navbar-header">
                            <!-- Toggle Button -->
                            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>
                        </div>

                        <div class="navbar-collapse collapse clearfix">
                            <?php echo $this->getLayout()->createBlock('core/template')->setTemplate('catalog/product/top_navigation1.phtml')->toHtml(); ?>
                        </div>
                    </nav>
                    <!-- Main Menu End-->
                </div>
                <!--Nav Outer End-->

            </div>
        </div>
    </div>

    <!--Sticky Header-->
    <div class="sticky-header">
        <div class="auto-container">

            <div class="outer-container clearfix">
                <!--Logo Box-->
                <div class="logo-box pull-left">
                    <div class="logo"><a href="https://www.socicos.com/Home"><img src="https://www.socicos.com/images/logo-small.png" alt=""></a></div>
                </div>

                <!--Nav Outer-->
                <div class="nav-outer clearfix">
                    <!-- Main Menu -->
                    <nav class="main-menu">
                        <div class="navbar-header">
                            <!-- Toggle Button -->
                            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>
                        </div>

                        <div class="navbar-collapse collapse clearfix">
                            <?php echo $this->getLayout()->createBlock('core/template')->setTemplate('catalog/product/top_navigation2.phtml')->toHtml(); ?>
                        </div>
                    </nav>
                    <!-- Main Menu End-->

                </div>
                <!--Nav Outer End-->

            </div>

        </div>
    </div>
    <!--End Sticky Header-->

</header>
<!--End Main Header --><section class="page-title" style="background-image:url(images/background/pattern-4.png);">
    <div class="auto-container">
        <h1>CONTENT MARKETING</h1>
    </div>
    <!--Page Info-->
    <div class="page-info">
        <div class="auto-container">
            <div class="inner-container">
                <ul class="bread-crumb">
                    <li><a href="https://www.socicos.com/Home">Home</a></li>
                    <li>CONTENT MARKETING</li>
                </ul>
            </div>
        </div>
    </div>
    <!--End Page Info-->
</section>
<!--End Page Title-->
<div class="sidebar-page-container">
    <div class="auto-container">
        <div class="row clearfix">

            <!--Content Side-->
            <div class="content-side col-lg-8 col-md-8 col-sm-12 col-xs-12">
                <!--Services Single-->
                <div class="services-single">
                    <div class="inner-box">
                        <h2>CONTENT MARKETING</h2>
                        <div class="lower-content">
                            <div class="text">
                                <h3>WHAT IS CONTENT MARKETING?</h3>
                                <p class="text-left"><strong>Content Marketing </strong>means creating and sharing valuable free content to attract and convert prospects into customers, and customers into repeat buyers. The type of content you share is closely related to what you sell; in other words, you’re educating people so that they know, like, and trust you enough to do business with you. </p>
                                <p class="text-left">If you’re interested in marketing your business online (and who isn’t at this point), you can’t escape hearing about content marketing. It’s everywhere you look, or listen.</p>
                                <h3>How to build a Successful Content Marketing Strategy in 7 Steps?</h3>
                                <p class="text-left">1-<strong>Plan- </strong>Who you are, Where you are, Where you want to be<br>
                                    2-<strong>Audience- </strong>Who you are, Where you are, Where you want to be<br>
                                    3-<strong>Story- </strong>Who you are, Where you are, Where you want to be<br>
                                    4-<strong>Channel- </strong>Who you are, Where you are, Where you want to be<br>
                                    5-<strong>Process- </strong>Who you are, Where you are, Where you want to be<br>
                                    6-<strong>Conversations- </strong>Who you are, Where you are, Where you want to be<br>
                                    7-<strong>Measurement- </strong>Who you are, Where you are, Where you want to be<br>
                                </p>
                                <h3>CONTENT TYPES</h3>
                                <p class="text-left">1-<strong>News- </strong>iamwire.com<br>
                                    2-<strong>Case studies- </strong>Salesforce.com<br>
                                    3-<strong>Reports- </strong>Socicos blog<br>
                                    4-<strong>Ebooks- </strong>Hubspot<br>
                                    5-<strong>Humor- </strong>Madovermarketing.com, wittyfeed.com, scoopwhoop.com<br>
                                    6-<strong>Videos- </strong>Hubspot TV<br>
                                    7-<strong>Webinars- </strong>Socialmediaexaminer.com<br>
                                    1-<strong>Podcasts- </strong>Jon loomer<br>
                                    2-<strong>E-magazines- </strong><br>
                                    3-<strong>How-to-guides- </strong>Hubspot<br>
                                    4-<strong>Events coverage- </strong>Mashable<br>
                                    5-<strong>Daily experiences- </strong><br>
                                    6-<strong>Answering questions- </strong>Quora<br>
                                    7-<strong>Examples from industry- </strong>yourstory.com<br>
                                    8-<strong>Guest posting- </strong>entrepreneur.com<br>
                                    9-<strong>Authority blog- </strong>hubspot<br>
                                </p>
                                <h3>Building an Authority Blog</h3>
                                <p class="text-left">An authority blog targets a specific market or group of like-minded individuals. It is designed to be the ultimate resource for that topic. Its primary goal isn’t to make an instant sale. Instead the site is used to educate the user in order to establish a long-term (but profitable) relationship.</p>
                                <p class="text-left"><strong>The Development Process</strong><br>There will be three phases for any new blog:</p>
                                <p class="text-left"><strong>Phase 1 – Building You Blog Site</strong><br>
                                    This will be pretty much like building a niche site. I will do basic stuff like:<br>
                                    •	Choosing domain and hosting. (subdomain or a new domain)<br>
                                    •	Setting up website. (Wordpress)<br>
                                    •	Content planning& keyword research. (Content marketing strategy 7 steps process)<br>
                                    •	Create publishing schedule (A routine of when what type of content will be posted and how it will be marketed)<br>
                                    •	Hiring content writers. (full-time/part-time from freelancer.com, elance.com, odesk.com, iwriter.com)<br>
                                    •	Creating rich valuable content. (new content or skyscraper method)<br>
                                    •	Marketing content.<br>
                                </p>
                                <p class="text-left"><strong>Phase 2 – Authority Building</strong><br>
                                    This phase will focus on creating massively valuable content that attract shares and links naturally. We will also start reaching out to bloggers and developing relationships with them for guest blogging opportunities.<br><br>
                                    Creating content consistently is also a MUST for this phase. Building an authority blog is like a marathon, not a sprint. And don’t forget that it is a long term process.<br>
                                </p>
                                <p class="text-left"><strong>Phase 3 – Monetize</strong><br>
                                    Although can start monetizing the site from day one with affiliate reviews/links/suggestions, But we would also begin to create my own products. <br>
                                </p>
                                <h3>How to Create Content that Isn’t a Joke?</h3>
                                <p class="text-left">1-<strong>Answering websites like yahoo Answers and quora.com: </strong>not just respond to questions but taking ideas from then on what to write about.<br>
                                    2-<strong>Set alerts like Google alerts,  </strong>en.mention.com, socialmention.com to keep a track on what people are talking about your industry.<br>
                                    3-<strong>Use keyword research tools</strong>like longtailpro.com or Google keyword planner tool to find search queries on Google<br>
                                    4-<strong>Contact people/companies in your industry to write about them</strong>(success stories, case studies, examples, Interviews)<br>
                                    5-<strong>Subscribe to good blogs in your industry </strong><br>
                                    6-<strong>Be updated for news and casestudies </strong><br>
                                    7-<strong>Be a good and active social animal</strong><br>
                                    8-<strong>Skyscraper technique </strong>This is a highly productive technique not just to find out what content to write about but to make your blog and authority blog. Content written via this technique often ranks well on search engines. In this technique we find top content on web for our keywords/area of interest and re-write it by updating it and adding things which can be added to make it even more comprehensive.<br>
                                    •	References used by Wikipedia<br>
                                    •	Google search<br>
                                    <br>
                                    9-<strong>Daily experiences </strong>Keep your eyes open and seek content opportunity while socializing. You meet all kinds of people daily in meetings, while commuting, in events, get together, etc. <br>
                                    10-<strong>Have expert people write for you </strong>- Hire experts from your industries to share their experiences with you via webinars, articles, interviews, etc<br>
                                    11-<strong>Be open for guest post </strong>Have a “write for us” page on your blog and let other guest bloggers reach you and write for you.<br>
                                </p>
                                <h3>How to market your content?</h3>
                                <p class="text-left">1-<strong>Social media</strong><br>- Facebook<br>
                                    -	Linkedin<br>
                                    -	Twitter<br>
                                    -	Linkedin<br>
                                    -	Instagram<br>
                                    2-<strong>Directories</strong><br>
                                    3-<strong>Multiple versions of same content</strong><br>
                                    4-<strong>Find who has linked to similar content in past</strong><br>
                                    5-<strong>Connect with Influencers </strong><br>
                                    6-<strong>Forums </strong><br>
                                    7-<strong>Guestpost</strong><br>
                                    8-<strong>Email</strong><br>
                                    9-<strong>Second customer </strong>Writing compelling content over a period of time will build lots of second customers for you which will help your content go places and increase its visibility
                                    <br>
                                </p>
                                <p class="text-left"><strong>Top 4 examples of content marketing</strong>1-	Rand Fiskin Whiteboard Fridays<br>
                                    2-	Hubspot TV<br>
                                    3-	Niel Patel legendry advanced guides<br>
                                    4-	Hubspot blog and promotion via opt-in<br>
                                </p>
                                <h3>HOW TO WRITE MAGNETIC HEADLINES</h3>
                                <p class="text-left">On average, 8 out of 10 people will read your headline copy, but only 2 out of10 will read the rest.</p>
                                <p class="text-left">Your headlines must:<br>
                                    •	Be USEFUL to the reader,<br>
                                    •	Provide him with a sense of URGENCY,<br>
                                    •	Convey the idea that the main benefit is somehow UNIQUE; and<br>
                                    How to Win Friends and Influence People<br>
                                    The headline structure is powerful.<br>
                                </p>
                                <p class="text-left"><strong>You’ve got benefit number one right after “How to,” with another benefit following the word “and.” Simple, right?</strong></p>
                                <p class="text-left">•	How to Save Time and Get Things Done (Time Management Coach)<br>
                                    •	How to Get a Better Job and Make More Money (Recruiter)<br>
                                    •	How to Save Money and Retire Rich (Financial Planner)<br>
                                </p>
                                <p class="text-left"><strong>How to [Mundane Task] That [Rewarding Benefit]</strong></p>
                                <p class="text-left">•	How to Get a Mortgage That Saves You Money<br>
                                    •	How to Get a Mortgage That Cuts your Monthly Payment in Half<br>
                                    •	How to Get a Mortgage That Gets You in Your Dream Home While Saving You $937 a Month<br>
                                </p>
                                <p class="text-left">In Summary<br>
                                    •	The more you focus on the benefits to the reader in your headline, the more readers you’ll have. And by touching on the beneficial aspects while laying out the procedural content, you’ll have more happy readers at the conclusion of the piece.
                                </p>
                                <h3>FEW MORE EXAMPLES-</h3>
                                <p class="text-left"><strong>1. Do You Recognize the 7 Early Warning Signs of High Blood Pressure?</strong><br>
                                    •	Use this type of headline to demonstrate the expertise that only comes from really knowing your business or niche. People love to get a “heads up” on potential problems.</p>
                                <p class="text-left"><strong>2. 10 Ways to Beat the High Cost of Living</strong><br>
                                    •	A classic that can only flop if you fail to deliver. Concentrate on writing content that sparkles, and people will acknowledge that you not only know what you’re talking about, but you also communicate it well.</p>
                                <p class="text-left"><strong>3. Five Familiar Skin Troubles</strong><br>
                                    •	Commiserate with your readers by setting forth problems you know they are having, and they just might determine that you are the right solution.</p>
                                <p class="text-left"><strong>4. Six Types of Investor — Which Group Are You In?</strong><br>
                                    •	Let the readers self-identify themselves by providing categories into which they will likely fall into. You know about the power of using the word “you” when addressing readers, but people love it even more when they can focus on themselves.</p>
                                <p class="text-left"><strong>5. How to Give Your Children Extra Iron — These 3 Delicious Ways</strong><br>
                                    •	A “how to” headline mixed in with a list — it’s almost not fair. Note that the word “these” plus the number of items, followed by “(adjective) ways,” is an extremely specific and powerful use of 4 simple words.</p>
                                <p class="text-left"><strong>6. Free Book Tells You 12 Secrets of Better Lawn Care</strong><br>
                                    •	Use this style of headline and content structure with a free report or tutorial that you are promoting, and you should get wider circulation.</p>
                                <p class="text-left"><strong>7. 76 Reasons Why It Would Have Paid You to Answer Our Ad a Few Months Ago</strong><br>
                                    •	An especially bold headline that worked wonders for a popular news magazine. The number of reasons given is so large it’s almost absurd, and that’s good from a value standpoint with free content. Plus, by referring back to previous ads, the piece points out the peril of not paying attention earlier.</p>
                                <h3>10 Sure-Fire Headline Formulas That Work</h3>
                                <p class="text-left"><strong>Who Else Wants [blank]?</strong><br>
                                    •	Who Else Wants a Great WordPress Theme?<br>
                                    •	Who Else Wants a Higher Paying Job?<br>
                                    •	Who Else Wants More Fun and Less Stress When on Vacation?<br>
                                </p>
                                <p class="text-left"><strong>The Secret of [blank]</strong><br>
                                    •	The Secret of Successful Podcasting <br>
                                    •	The Secret of Protecting Your Assets in Litigation <br>
                                    •	The Secret of Getting Your Home Loan Approved <br>
                                </p>
                                <p class="text-left"><strong>Here is a Method That is Helping [blank] to [blank]</strong><br>
                                    •	Here is a Method That is Helping Homeowners Save Hundreds on Insurance <br>
                                    •	Here is a Method That is Helping Children Learn to Read Sooner <br>
                                    •	Here is a Method That is Helping Bloggers Write Better Post Titles <br>
                                </p>
                                <p class="text-left"><strong>Little Known Ways to [blank]</strong><br>
                                    •	Little Known Ways to Save on Your Heating Bill <br>
                                    •	Little Known Ways to Hack Google’s Gmail <br>
                                    •	Little Known Ways to Lose Weight Quickly and Safely <br>
                                </p>
                                <p class="text-left"><strong>Get Rid of [problem] Once and For All</strong><br>
                                    •	Get Rid of Your Unproductive Work Habits Once and For All  <br>
                                    •	Get Rid of That Carpet Stain Once and For All  <br>
                                    •	Get Rid of That Lame Mullet Hairdo Once and For All  <br>
                                </p>
                                <p class="text-left"><strong>Here’s a Quick Way to [solve a problem]</strong><br>
                                    •	Here’s a Quick Way to Get Over a Cold  <br>
                                    •	Here’s a Quick Way to Potty Train Junior <br>
                                    •	Here’s a Quick Way to Backup Your Hard Drive  <br>
                                </p>
                                <p class="text-left"><strong>Now You Can Have [something desirable] [great circumstance]</strong><br>
                                    •	Now You Can Quit Your Job and Make Even More Money  <br>
                                    •	Now You Can Meet Sexy Singles Online Without Spending a Dime  <br>
                                    •	Now You Can Own a Cool Mac and Still Run Windows  <br>
                                </p>
                                <p class="text-left"><strong>[Do something] like [world-class example]</strong><br>
                                    •	Speak Spanish Like a Diplomat  <br>
                                    •	Party Like Paris Hilton   <br>
                                    •	Blog Like an A-Lister  <br>
                                </p>
                                <p class="text-left"><strong>Have a [or] Build a [blank] You Can Be Proud Of</strong><br>
                                    •	Build a Body You Can Be Proud Of <br>
                                    •	Have a Smile You Can Be Proud Of <br>
                                    •	Build a Blog Network You Can Be Proud Of  <br>
                                </p>
                                <p class="text-left"><strong>What Everybody Ought to Know About [blank]</strong><br>
                                    •	What Everybody Ought to Know About Mobile-Responsive Design <br>
                                    •	What Everybody Ought to Know About Adjustable Rate Mortgages <br>
                                    •	What Everybody Ought to Know About Writing Great Headlines <br>
                                </p>
                                <p class="text-left"><strong>Give Me [short time period] and I’ll Give You [blank].</strong><br>
                                    •	Give Me Five Days – And I’ll Give You the Secret of Learning any Subject!  <br>
                                    •	Give Me Three Minutes a Day – and I’ll Give You a Better Complexion.    <br>
                                    •	Give Me 3 Minutes and I’ll Make You a Better Blogger.  <br>
                                </p>
                                <p class="text-left"><strong>If You Don’t [blank] Now, You’ll Hate Yourself Later.</strong><br>
                                    •	If You’re Out of the Market Now, You’ll Hate Yourself Later.  <br>
                                    •	If You’re Not at SXSW 2014, You’ll Hate Yourself Later.  <br>
                                    •	If You Don’t Edit Your .htaccess Now, Google Will Hate You Later.  <br>
                                </p>
                                <p class="text-left"><strong>The Lazy [blank’s] Way to [blank].</strong><br>
                                    •	The Lazy Man’s Way to Riches.  <br>
                                    •	The Lazy Dad’s Way to Quickly Getting Dinner on the Table.  <br>
                                    •	The Lazy Blogger’s Way to Write Great Post Titles.  <br>
                                </p>
                                <p class="text-left"><strong>Do You Recognize the [number] Early Warning Signs of [blank]?</strong><br>
                                    •	Do You Recognize the 7 Early Warning Signs of High Blood Pressure?   <br>
                                    •	Do You Recognize the 7 Early Warning Signs of an Employee Meltdown?   <br>
                                    •	Do You Recognize the 7 Early Warning Signs of Internet Addiction?  <br>
                                </p>
                                <p class="text-left"><strong>See How Easily You Can [desirable result].</strong><br>
                                    •	See How Easily You Can Learn to Dance This New Way.  <br>
                                    •	See How Easily You Can Own a Lamborghini Miura.  <br>
                                    •	See How Easily You Can Increase Traffic With Social Media.  <br>
                                </p>
                                <p class="text-left"><strong>Do You Make These Mistakes?</strong><br>
                                    •	Do You Make These Mistakes in English?  <br>
                                    •	Do You Make These HTML Coding Mistakes? <br>
                                    •	Do You Make These Mistakes With Your Blog?  <br>
                                </p>
                                <p class="text-left"><strong>Warning: [blank].</strong><br>
                                    •	Warning: If You Depend on Google for Both Traffic and Advertising, You Pretty Much Work for Google  <br>
                                    •	Warning: Two Out of Every Three People in Your Industry Will be Out of Work in 5 Years—Will You Be One of Them?  <br>
                                    •	Warning: Do You Recognize These 7 Early Warning Signs of Blogger Burnout?  <br>
                                </p>
                                <p class="text-left"><strong>How [blank] Made Me [blank].</strong><br>
                                    •   How a “Fool Stunt” Made Me a Star Salesman  <br>
                                    •	How an Obvious Idea Made Me $3.5 Million  <br>
                                </p>
                                <p class="text-left"><strong>Are You [blank]?</strong><br>
                                    •	Are You Ashamed of Smells in Your House?   <br>
                                    •	Are You Ready to Learn Chinese for Your Next Job?   <br>
                                    •	Are You a Courageous Blogger? <br>
                                </p>
                                <p class="text-left"><strong>[Blank] Ways to [blank].</strong><br>
                                    •	101 Ways to Cope With Stress  <br>
                                    •	21 Ways to Live a Better Life With Less <br>
                                    •	5 Ways to Write Killer Headlines   <br>
                                </p>
                                <p class="text-left"><strong>If You’re [blank], You Can [blank].</strong><br>
                                    •   If You’re a Non-Smoker, You Can Save 33% on Life Insurance.  <br>
                                    •	If You’re an Accountant, Our Frequent Flyer Program Really Adds Up   <br>
                                    •	If You Love Scuba, You Can Dive Belize This Week Only for a Song!  <br>
                                </p>
                                <h3>8 Proven Headline Formulas That Sell Like Crazy</h3>
                                <p class="text-left"><strong>Say it simply and directly.</strong><br>
                                    •	Pure silk blouses - 30% off  <br>
                                    •	The Ultimate Tax Shelter  <br>
                                    •	FREE subscription to Entre producer<br>
                                </p>
                                <p class="text-left"><strong>State the big benefit.</strong><br>
                                    •	Now! Moonlight Your Way to a Million Dollars. <br>
                                    •	Create your own cards, posters and banners in minutes!  <br>
                                    •	Get a FREE vase when you buy a dozen roses.  <br>
                                </p>
                                <p class="text-left"><strong>Announce exciting news.</strong><br>
                                    •	At Last, American Scientists Have Created the Perfect Alternative to a Mined Diamond!  <br>
                                    •	Introducing the newest idea in cross-training. From NordicTrack.  <br>
                                    •	Now program your DVR by simply speaking to the revolutionary DVR VOICE programmer. <br>
                                </p>
                                <p class="text-left"><strong>Appeal to the “how-to” instinct.</strong><br>
                                    •	How to stop smoking in 30 days ... or your money back. <br>
                                    •	How You Can Profit From the 3 Greatest Service Businesses of the Decade!   <br>
                                    •	How to do Central America on $17 a day.  <br>
                                </p>
                                <p class="text-left"><strong>Pose a provocative question.</strong><br>
                                    •	Do You Make These Six Common Mistakes On Your Taxes?  <br>
                                    •	Gotten a speeding ticket lately? Read this. <br>
                                    •	How do I know which mutual funds may be right for me? <br>
                                </p>
                                <p class="text-left"><strong>Bark a command.</strong><br>
                                    •	Become a famous blogger in 60 days.  <br>
                                    •	Call anyone, anywhere, without a phone line for FREE!   <br>
                                    •	Stop wasting money on Web design. Use StudioPress to create your own Web site in minutes.  <br>
                                </p>
                                <p class="text-left"><strong>Offer useful information.</strong><br>
                                    •	THE 20 MOST IMPORTANT STEPS YOU CAN TAKE TO LIVE LONGER.  <br>
                                    •	FREE. The best kept secrets in America.   <br>
                                    •	Free brochure shows you how to end your money worries for good. <br>
                                </p>
                                <p class="text-left"><strong>Relay an honest, enthusiastic testimonial. “Quite simply, the finest design software ever released.” </strong><br>
                                    •	“This diet program worked for me. It can work for you, too!”  <br>
                                    •	“It’s the first book on personal finance that really made sense to me.” <br>
                                </p>
                                <a href="#" class="theme-btn btn-style-one start-btn">Start Yours</a>
                                <h3>SEO Services</h3>
                                <p>Desires to obtain pain of itself, because it is pain, but because occasionally circumstances occur in which toil and pain can procure him some great pleasure example, which of us ever undertakes.</p>
                            </div>
                            <!--Two Column-->


                        </div>
                    </div>
                </div>
            </div>
            <!--Sidebar Side-->
            <div class="sidebar-side col-lg-4 col-md-4 col-sm-12 col-xs-12">
                <aside class="sidebar default-sidebar with-border">
                    <!-- Search -->
                    <!--Blog Category Widget-->
                    <!--Recent Comments-->
                    <div class="sidebar-widget recent-comments" style="left: 120px;">
                        <div class="sidebar-title" style="left: 37px;">
                            <h2>Resources</h2>
                        </div>
                        <ul class="blog-cat-two">
                            <li><a href="https://www.socicos.com/Management/socialmediamanagement">SOCIAL MEDIA MANAGEMENT</a></li>
                           <!-- <li><a href="#">SEARCH ENGINE OPTIMIZATION</a></li>
                            <li><a href="#">SEARCH ENGINE MARKETING</a></li>
                            <li><a href="#">GOOGLE ANALYTICS</a></li>
                            <li><a href="#">YOUTUBE MARKETING</a></li>-->
                            <li><a href="https://www.socicos.com/Management/leadgeneration">LEAD GENERATION</a></li>
                            <!--<li><a href="#">CONTENT MARKETING</a></li>
                            <li><a href="#">EMAIL MARKETING</a></li>
                            <li><a href="#">WEBSITE TRAFFIC</a></li>
                            <li><a href="#">DISPLAY ADVERTISING</a></li>
                            <li><a href="#">DIRECTORY SUBMISSION LIST</a></li>
                            <li><a href="#">ONLINE REPUTATION MANAGEMENT</a></li>-->
                            <li><a href="https://www.socicos.com/Management/mobilemarketing">MOBILE WEB MARKETING</a></li>
                           <!-- <li><a href="#">E-COMMERCE MARKETING</a></li>
                            <li><a href="#">INFLUENCER MARKETING</a></li>
                            <li><a href="#">ADSENCE & BLOGGING</a></li>-->
                            <li><a href="https://www.socicos.com/Management/websitedesigndevelopement">WEBSITE DESIGN & DEVELOPMENT</a></li>
                           <!-- <li><a href="#">APP DESIGN & DEVELOPMENT</a></li>
                            <li><a href="#">IN-APP ADVERTISING</a></li>-->
                            <li><a href="https://www.socicos.com/Management/tasktracking">TASK TRACKING & REMINDERS</a></li>
                            <!--<li><a href="#">SALES LANDING PAGE</a></li>
                            <li><a href="#">INDIVIDUAL MARKETING STRATEGY</a></li>-->
                            <li><a href="https://www.socicos.com/Management/smsmarketing">SMS MARKETING</a></li>
                            <!--<a href="#">CROWDFUNDING A BUSINESS</a></li>
                            <li><a href="#">DROPSHIPPING</a></li>-->
                            <li><a href="https://www.socicos.com/Management/affiliatemarketing">AFFILIATE MARKETING</a></li>
                            <!--<li><a href="#">MARKETING INVESTMENTS</a></li>
                            <li><a href="#">SURVEY MARKETING</a></li>
                            <li><a href="#">ONLINE OR OFFLINE EVENT PRTICIPATION</a></li>
                            <li><a href="#">PLR ARTICLES</a></li>
                            <li><a href="#">EMAIL ID & MOBILE NO. DATABASE</a></li>
                            <li><a href="#">GOOGLE PARTNER</a></li>-->
                            <li><a href="https://www.socicos.com/Management/digitalmarketing">DIGITAL MARKETING TOOLS</a></li>
                            <!--<li><a href="#">FREELANCE</a></li>
                            <li><a href="#">APPLY FOR A DIGITAL MARKETING JOB</a></li>-->
                        </ul>
                    </div>
                    <!-- Popular Posts -->
                    <!-- Popular Tags -->
                </aside>
            </div>

        </div>
    </div>
</div></section>
<!--End Partners Section-->

<!--Main Footer-->
<footer class="main-footer">
    <div class="auto-container">

        <!--Widgets Section-->
        <div class="widgets-section">
            <div class="row clearfix">

                <!--Column-->
                <div class="column col-md-4 col-sm-6 col-xs-12">
                    <div class="footer-widget links-widget">
                        <div class="footer-title">
                            <h2>Usefull Links</h2>
                        </div>
                        <div class="widget-content">
                            <div class="row clearfix">
                                <div class="widget-column col-md-6 col-sm-6 col-xs-12">
                                    <ul class="footer-list">
                                        <li><a href="https://www.socicos.com/Home">Home</a></li>
                                        <li><a href="https://www.socicos.com/Aboutus">About Us</a></li>
                                        <li><a href="https://www.socicos.com/Tools">Tools</a></li>
                                        <li><a href="https://www.socicos.com/Howitworks">How it Works?</a></li>
                                        <li><a href="https://www.socicos.com/Management">Resources</a></li>
                                        <li><a href="https://www.socicos.com/Contactus">Contact Us</a></li>
                                    </ul>
                                </div>
                                <div class="widget-column col-md-6 col-sm-6 col-xs-12">
                                    <ul class="footer-list">
                                        <li><a target="_blank" href="http://app.socicos.com/">Login</a></li>
                                        <li><a target="_blank" href="http://app.socicos.com/Socialregistration">Register</a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <!--Column-->
                <div class="column col-md-4 col-sm-6 col-xs-12">
                    <div class="footer-widget subscribe-widget">
                        <div class="footer-title">
                            <h2>Subscribe Us</h2>
                        </div>
                        <div class="widget-content">
                            <div class="text">Subscribe us for recieve latest Updates <br> News and Offers.</div>
                            <div class="subscribe-form">
                                <form method="post" action="contact.html">
                                    <div class="form-group">
                                        <input type="email" name="email" value="" placeholder="Email Address..." required="">
                                        <button type="submit" class="theme-btn"><span class="flaticon-right-arrow-1"></span></button>
                                    </div>
                                </form>
                            </div>
                            <ul class="social-icon-one">
                                <li><a href="#"><span class="fa fa-facebook-f"></span></a></li>
                                <li><a href="#"><span class="fa fa-twitter"></span></a></li>
                                <li><a href="#"><span class="fa fa-linkedin"></span></a></li>
                                <li><a href="#"><span class="fa fa-rss"></span></a></li>
                                <li><a href="#"><span class="fa fa-google-plus"></span></a></li>
                                <li><a href="#"><span class="fa fa-vimeo"></span></a></li>
                            </ul>
                        </div>
                    </div>
                </div>

                <!--Column-->
                <div class="column col-md-4 col-sm-6 col-xs-12">
                    <div class="footer-widget office-widget">
                        <div class="footer-title">
                            <h2>Corporate Office</h2>
                        </div>
                        <div class="widget-content">
                            <div class="single-item-carousel owl-carousel owl-theme">

                                <div class="office-info">
                                    <ul>
                                        <li><strong>Address:</strong></li>
                                        <li>3rd Floor, SuryaPrema
                                            #15, Plot No 1 & 2, 1st Cross, Manjunathanagar, Kanakpura Road, Bengaluru, Karnataka 560062</li>
                                        <li><a href="#">Find Us On Map</a></li>
                                    </ul>
                                </div>

                                <div class="office-info">
                                    <ul>
                                        <li><strong>Address:</strong></li>
                                        <li>3rd Floor, SuryaPrema
                                            #15, Plot No 1 & 2, 1st Cross, Manjunathanagar, Kanakpura Road, Bengaluru, Karnataka 560062 </li>
                                        <li><a href="#">Find Us On Map</a></li>
                                    </ul>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>

    </div>
    <!--Copyright-->
    <div class="copyright">Copyright &copy; 2012-2018 The SOCICOS. All rights reserved.</div>
</footer>
<!--Main Footer-->
<!--Bottom Parallax-->

</div>
<!--End pagewrapper-->

<!--Scroll to top-->
<div class="scroll-to-top scroll-to-target" data-target="html"><span class="icon fa fa-angle-double-up"></span></div>

<script src="https://www.socicos.com/js/jquery.js"></script>
<!--Revolution Slider-->
<script src="https://www.socicos.com/assets/revolution/js/jquery.themepunch.revolution.min.js"></script>
<script src="https://www.socicos.com/assets/revolution/js/jquery.themepunch.tools.min.js"></script>
<script src="https://www.socicos.com/assets/revolution/js/extensions/revolution.extension.actions.min.js"></script>
<script src="https://www.socicos.com/assets/revolution/js/extensions/revolution.extension.carousel.min.js"></script>
<script src="https://www.socicos.com/assets/revolution/js/extensions/revolution.extension.kenburn.min.js"></script>
<script src="https://www.socicos.com/assets/revolution/js/extensions/revolution.extension.layeranimation.min.js"></script>
<script src="https://www.socicos.com/assets/revolution/js/extensions/revolution.extension.migration.min.js"></script>
<script src="https://www.socicos.com/assets/revolution/js/extensions/revolution.extension.navigation.min.js"></script>
<script src="https://www.socicos.com/assets/revolution/js/extensions/revolution.extension.parallax.min.js"></script>
<script src="https://www.socicos.com/assets/revolution/js/extensions/revolution.extension.slideanims.min.js"></script>
<script src="https://www.socicos.com/assets/revolution/js/extensions/revolution.extension.video.min.js"></script>
<script src="https://www.socicos.com/js/main-slider-script.js"></script>

<script src="https://www.socicos.com/js/jquery.js"></script>
<script src="https://www.socicos.com/js/bootstrap.min.js"></script>
<script src="https://www.socicos.com/js/jquery.fancybox.pack.js"></script>
<script src="https://www.socicos.com/js/jquery.fancybox-media.js"></script>
<script src="https://www.socicos.com/js/owl.js"></script>
<script src="https://www.socicos.com/js/wow.js"></script>
<script src="https://www.socicos.com/js/validate.js"></script>
<script src="https://www.socicos.com/js/jquery-ui.js"></script>
<script src="https://www.socicos.com/js/knob.js"></script>
<script src="https://www.socicos.com/js/slick.js"></script>
<script src="https://www.socicos.com/js/appear.js"></script>
<script src="https://www.socicos.com/js/script.js"></script>
<!--<script src="https://www.socicos.com/js/validate.js"></script>-->
<script src="http://maps.google.com/maps/api/js?key=AIzaSyBKS14AnP3HCIVlUpPKtGp7CbYuMtcXE2o"></script>
<script src="https://www.socicos.com/js/map-script.js"></script>

<!--Scroll to top-->
<div class="scroll-to-top scroll-to-target" data-target="html"><span class="icon fa fa-angle-double-up"></span></div>


</body>
</html>