<?php $path = Mage::getBaseUrl( Mage_Core_Model_Store::URL_TYPE_WEB, true ) . 'socicos/'; ?>
<!DOCTYPE html>
<html>
    <?php echo $this->getLayout()->createBlock('core/template')->setTemplate('catalog/product/head.phtml')->toHtml(); ?>
    <body>
        <div class="page-wrapper">
            <!-- Preloader -->
            <div class="preloader"></div>
            <!-- Main Header-->
            <?php echo $this->getLayout()->createBlock('core/template')->setTemplate('catalog/product/header.phtml')->toHtml(); ?>
            <!--End Main Header -->

        <!--End Main Header --><!--Main Slider-->
        <section class="main-slider">

            <div class="rev_slider_wrapper fullwidthbanner-container"  id="rev_slider_two_wrapper" data-source="gallery">
                <div class="rev_slider fullwidthabanner" id="rev_slider_two" data-version="5.4.1">
                    <ul>
                        <li data-description="Slide Description" data-easein="default" data-easeout="default" data-fsmasterspeed="1500" data-fsslotamount="7" data-fstransition="fade" data-hideafterloop="0" data-hideslideonmobile="off" data-index="rs-1688" data-masterspeed="default" data-param1="" data-param10="" data-param2="" data-param3="" data-param4="" data-param5="" data-param6="" data-param7="" data-param8="" data-param9="" data-rotate="0" data-saveperformance="off" data-slotamount="default" data-thumb="<?php echo $path; ?>images/main-slider/image-1.jpg" data-title="Slide Title" data-transition="parallaxvertical">
                            <img alt="" class="rev-slidebg" data-bgfit="cover" data-bgparallax="10" data-bgposition="center center" data-bgrepeat="no-repeat" data-no-retina="" src="<?php echo $path; ?>images/main-slider/image-1.jpg">

                            <div class="tp-caption"
                                 data-paddingbottom="[0,0,0,0]"
                                 data-paddingleft="[0,0,0,0]"
                                 data-paddingright="[0,0,0,0]"
                                 data-paddingtop="[0,0,0,0]"
                                 data-responsive_offset="on"
                                 data-type="text"
                                 data-height="none"
                                 data-width="['560','700','700','550']"
                                 data-whitespace="normal"
                                 data-hoffset="['15','15','15','15']"
                                 data-voffset="['-30','-90','-90','-60']"
                                 data-x="['left','left','left','left']"
                                 data-y="['middle','middle','middle','middle']"
                                 data-textalign="['top','top','top','top']"
                                 data-frames='[{"from":"y:[-100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;","mask":"x:0px;y:0px;s:inherit;e:inherit;","speed":1500,"to":"o:1;","delay":1000,"ease":"Power3.easeInOut"},{"delay":"wait","speed":1000,"to":"auto:auto;","mask":"x:0;y:0;s:inherit;e:inherit;","ease":"Power3.easeInOut"}]'>
                                <h2><span>best</span>Digital Marketing Tool Online</p> for Entrepreneur</h2>
                            </div>

                            <div class="tp-caption"
                                 data-paddingbottom="[0,0,0,0]"
                                 data-paddingleft="[0,0,0,0]"
                                 data-paddingright="[0,0,0,0]"
                                 data-paddingtop="[0,0,0,0]"
                                 data-responsive_offset="on"
                                 data-type="text"
                                 data-height="none"
                                 data-width="['470','700','700','550']"
                                 data-whitespace="normal"
                                 data-hoffset="['15','15','15','15']"
                                 data-voffset="['40','40','20','0']"
                                 data-x="['left','left','left','left']"
                                 data-y="['middle','middle','middle','middle']"
                                 data-textalign="['top','top','top','top']"
                                 data-frames='[{"from":"y:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;","mask":"x:0px;y:0px;s:inherit;e:inherit;","speed":1500,"to":"o:1;","delay":1000,"ease":"Power3.easeInOut"},{"delay":"wait","speed":1000,"to":"auto:auto;","mask":"x:0;y:0;s:inherit;e:inherit;","ease":"Power3.easeInOut"}]'>
                                <div class="text">We Offering the best tool that can be tailored to suit any business & budget.</div>
                            </div>
                            <div class="tp-caption tp-resizeme"
                                 data-paddingbottom="[0,0,0,0]"
                                 data-paddingleft="[0,0,0,0]"
                                 data-paddingright="[0,0,0,0]"
                                 data-paddingtop="[0,0,0,0]"
                                 data-responsive_offset="on"
                                 data-type="text"
                                 data-height="none"
                                 data-width="['560','700','700','550']"
                                 data-whitespace="normal"
                                 data-hoffset="['15','15','15','15']"
                                 data-voffset="['130','150','120','100']"
                                 data-x="['left','left','left','left']"
                                 data-y="['middle','middle','middle','middle']"
                                 data-textalign="['top','top','top','top']"
                                 data-frames='[{"from":"y:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;","mask":"x:0px;y:0px;s:inherit;e:inherit;","speed":1500,"to":"o:1;","delay":1000,"ease":"Power3.easeInOut"},{"delay":"wait","speed":1000,"to":"auto:auto;","mask":"x:0;y:0;s:inherit;e:inherit;","ease":"Power3.easeInOut"}]'>
                                <!--<div class="btns-box">
                                    <a href="<?php echo $path; ?>Management/digitalmarketing" class="theme-btn btn-style-one"> <span class="icon flaticon-right-arrow-1"></span> Read More</a>
                                </div>-->
                            </div>
                            <div class="tp-caption tp-shape tp-shapewrapper tp-resizeme"
                                 data-paddingbottom="[0,0,0,0]"
                                 data-paddingleft="[0,0,0,0]"
                                 data-paddingright="[0,0,0,0]"
                                 data-paddingtop="[0,0,0,0]"
                                 data-responsive_offset="on"
                                 data-type="shape"
                                 data-height="auto"
                                 data-whitespace="nowrap"
                                 data-width="none"
                                 data-hoffset="['15','15','15','15']"
                                 data-voffset="['20','15','15','15']"
                                 data-x="['right','right','right','right']"
                                 data-y="['middle','middle','middle','middle']"
                                 data-frames='[{"from":"x:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;","mask":"x:0px;y:0px;s:inherit;e:inherit;","speed":1000,"to":"o:1;","delay":1000,"ease":"Power3.easeInOut"},{"delay":"wait","speed":1000,"to":"auto:auto;","mask":"x:0;y:0;s:inherit;e:inherit;","ease":"Power3.easeInOut"}]'>
                                <figure class="content-image"><img src="<?php echo $path; ?>images/main-slider/content-image-1.png" alt=""></figure>
                            </div>
                        </li>

                        <li data-description="Slide Description" data-easein="default" data-easeout="default" data-fsmasterspeed="1500" data-fsslotamount="7" data-fstransition="fade" data-hideafterloop="0" data-hideslideonmobile="off" data-index="rs-1689" data-masterspeed="default" data-param1="" data-param10="" data-param2="" data-param3="" data-param4="" data-param5="" data-param6="" data-param7="" data-param8="" data-param9="" data-rotate="0" data-saveperformance="off" data-slotamount="default" data-thumb="images/main-slider/image-2.jpg" data-title="Slide Title" data-transition="parallaxvertical">
                            <img alt="" class="rev-slidebg" data-bgfit="cover" data-bgparallax="10" data-bgposition="center center" data-bgrepeat="no-repeat" data-no-retina="" src="<?php echo $path; ?>images/main-slider/image-2.jpg">

                            <div class="tp-caption"
                                 data-paddingbottom="[0,0,0,0]"
                                 data-paddingleft="[0,0,0,0]"
                                 data-paddingright="[0,0,0,0]"
                                 data-paddingtop="[0,0,0,0]"
                                 data-responsive_offset="on"
                                 data-type="text"
                                 data-height="none"
                                 data-width="['560','700','700','550']"
                                 data-whitespace="normal"
                                 data-hoffset="['15','15','15','15']"
                                 data-voffset="['-30','-50','-50','-50']"
                                 data-x="['right','right','right','left']"
                                 data-y="['middle','middle','middle','middle']"
                                 data-textalign="['top','top','top','top']"
                                 data-frames='[{"from":"y:[-100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;","mask":"x:0px;y:0px;s:inherit;e:inherit;","speed":1500,"to":"o:1;","delay":1000,"ease":"Power3.easeInOut"},{"delay":"wait","speed":1000,"to":"auto:auto;","mask":"x:0;y:0;s:inherit;e:inherit;","ease":"Power3.easeInOut"}]'>
                                <h2 class="light"><span>Social </span> Media Management</h2>
                            </div>

                            <div class="tp-caption"
                                 data-paddingbottom="[0,0,0,0]"
                                 data-paddingleft="[0,0,0,0]"
                                 data-paddingright="[0,0,0,0]"
                                 data-paddingtop="[0,0,0,0]"
                                 data-responsive_offset="on"
                                 data-type="text"
                                 data-height="none"
                                 data-width="['560','700','700','550']"
                                 data-whitespace="normal"
                                 data-hoffset="['15','15','15','15']"
                                 data-voffset="['40','20','20','15']"
                                 data-x="['right','right','right','left']"
                                 data-y="['middle','middle','middle','middle']"
                                 data-textalign="['top','top','top','top']"
                                 data-frames='[{"from":"y:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;","mask":"x:0px;y:0px;s:inherit;e:inherit;","speed":1500,"to":"o:1;","delay":1000,"ease":"Power3.easeInOut"},{"delay":"wait","speed":1000,"to":"auto:auto;","mask":"x:0;y:0;s:inherit;e:inherit;","ease":"Power3.easeInOut"}]'>
                                <div class="text light">Manage all your Social Media Accounts at one Platform to save your Time & Money.</div>
                            </div>

                            <div class="tp-caption tp-resizeme"
                                 data-paddingbottom="[0,0,0,0]"
                                 data-paddingleft="[0,0,0,0]"
                                 data-paddingright="[0,0,0,0]"
                                 data-paddingtop="[0,0,0,0]"
                                 data-responsive_offset="on"
                                 data-type="text"
                                 data-height="none"
                                 data-width="['560','700','700','550']"
                                 data-whitespace="normal"
                                 data-hoffset="['15','15','15','15']"
                                 data-voffset="['130','100','100','100']"
                                 data-x="['right','right','right','left']"
                                 data-y="['middle','middle','middle','middle']"
                                 data-textalign="['top','top','top','top']"
                                 data-frames='[{"from":"y:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;","mask":"x:0px;y:0px;s:inherit;e:inherit;","speed":1500,"to":"o:1;","delay":1000,"ease":"Power3.easeInOut"},{"delay":"wait","speed":1000,"to":"auto:auto;","mask":"x:0;y:0;s:inherit;e:inherit;","ease":"Power3.easeInOut"}]'>
                                <!--<div class="btns-box">
                                    <a href="<?php echo $path; ?>Management/socialmediamanagement" class="theme-btn btn-style-one"> <span class="icon flaticon-right-arrow-1"></span> Read More</a>
                                </div>-->
                            </div>

                            <div class="tp-caption tp-shape tp-shapewrapper tp-resizeme"
                                 data-paddingbottom="[0,0,0,0]"
                                 data-paddingleft="[0,0,0,0]"
                                 data-paddingright="[0,0,0,0]"
                                 data-paddingtop="[0,0,0,0]"
                                 data-responsive_offset="on"
                                 data-type="shape"
                                 data-height="auto"
                                 data-whitespace="nowrap"
                                 data-width="none"
                                 data-hoffset="['15','15','15','15']"
                                 data-voffset="['20','0','0','0']"
                                 data-x="['left','left','left','left']"
                                 data-y="['middle','middle','middle','middle']"
                                 data-frames='[{"from":"x:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;","mask":"x:0px;y:0px;s:inherit;e:inherit;","speed":1000,"to":"o:1;","delay":1000,"ease":"Power3.easeInOut"},{"delay":"wait","speed":1000,"to":"auto:auto;","mask":"x:0;y:0;s:inherit;e:inherit;","ease":"Power3.easeInOut"}]'>
                                <figure class="content-image"><img src="<?php echo $path; ?>images/main-slider/content-image-2.png" alt=""></figure>
                            </div>

                        </li>

                        <li data-description="Slide Description" data-easein="default" data-easeout="default" data-fsmasterspeed="1500" data-fsslotamount="7" data-fstransition="fade" data-hideafterloop="0" data-hideslideonmobile="off" data-index="rs-1690" data-masterspeed="default" data-param1="" data-param10="" data-param2="" data-param3="" data-param4="" data-param5="" data-param6="" data-param7="" data-param8="" data-param9="" data-rotate="0" data-saveperformance="off" data-slotamount="default" data-thumb="images/main-slider/image-3.jpg" data-title="Slide Title" data-transition="parallaxvertical">
                            <img alt="" class="rev-slidebg" data-bgfit="cover" data-bgparallax="10" data-bgposition="center center" data-bgrepeat="no-repeat" data-no-retina="" src="<?php echo $path; ?>images/main-slider/image-3.jpg">

                            <div class="tp-caption"
                                 data-paddingbottom="[0,0,0,0]"
                                 data-paddingleft="[0,0,0,0]"
                                 data-paddingright="[0,0,0,0]"
                                 data-paddingtop="[0,0,0,0]"
                                 data-responsive_offset="on"
                                 data-type="text"
                                 data-height="none"
                                 data-width="['560','700','700','550']"
                                 data-whitespace="normal"
                                 data-hoffset="['15','15','15','15']"
                                 data-voffset="['-30','-90','-90','-60']"
                                 data-x="['left','left','left','left']"
                                 data-y="['middle','middle','middle','middle']"
                                 data-textalign="['top','top','top','top']"
                                 data-frames='[{"from":"y:[-100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;","mask":"x:0px;y:0px;s:inherit;e:inherit;","speed":1500,"to":"o:1;","delay":1000,"ease":"Power3.easeInOut"},{"delay":"wait","speed":1000,"to":"auto:auto;","mask":"x:0;y:0;s:inherit;e:inherit;","ease":"Power3.easeInOut"}]'>
                                <h2><span>Website</span>Analysis</h2>
                            </div>

                            <div class="tp-caption"
                                 data-paddingbottom="[0,0,0,0]"
                                 data-paddingleft="[0,0,0,0]"
                                 data-paddingright="[0,0,0,0]"
                                 data-paddingtop="[0,0,0,0]"
                                 data-responsive_offset="on"
                                 data-type="text"
                                 data-height="none"
                                 data-width="['470','700','700','550']"
                                 data-whitespace="normal"
                                 data-hoffset="['15','15','15','15']"
                                 data-voffset="['30','40','20','0']"
                                 data-x="['left','left','left','left']"
                                 data-y="['middle','middle','middle','middle']"
                                 data-textalign="['top','top','top','top']"
                                 data-frames='[{"from":"y:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;","mask":"x:0px;y:0px;s:inherit;e:inherit;","speed":1500,"to":"o:1;","delay":1000,"ease":"Power3.easeInOut"},{"delay":"wait","speed":1000,"to":"auto:auto;","mask":"x:0;y:0;s:inherit;e:inherit;","ease":"Power3.easeInOut"}]'>
                                <div class="text">Analyse your website to know how good your website composed to your competitors.</div>
                            </div>

                            <div class="tp-caption tp-resizeme"
                                 data-paddingbottom="[0,0,0,0]"
                                 data-paddingleft="[0,0,0,0]"
                                 data-paddingright="[0,0,0,0]"
                                 data-paddingtop="[0,0,0,0]"
                                 data-responsive_offset="on"
                                 data-type="text"
                                 data-height="none"
                                 data-width="['560','700','700','550']"
                                 data-whitespace="normal"
                                 data-hoffset="['15','15','15','15']"
                                 data-voffset="['120','150','120','100']"
                                 data-x="['left','left','left','left']"
                                 data-y="['middle','middle','middle','middle']"
                                 data-textalign="['top','top','top','top']"
                                 data-frames='[{"from":"y:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;","mask":"x:0px;y:0px;s:inherit;e:inherit;","speed":1500,"to":"o:1;","delay":1000,"ease":"Power3.easeInOut"},{"delay":"wait","speed":1000,"to":"auto:auto;","mask":"x:0;y:0;s:inherit;e:inherit;","ease":"Power3.easeInOut"}]'>
                                <!--<div class="btns-box">
                                    <a href="<?php echo $path; ?>Management/websitedesigndevelopement" class="theme-btn btn-style-one"> <span class="icon flaticon-right-arrow-1"></span> Read More</a>
                                </div>-->
                            </div>

                            <div class="tp-caption tp-shape tp-shapewrapper tp-resizeme"
                                 data-paddingbottom="[0,0,0,0]"
                                 data-paddingleft="[0,0,0,0]"
                                 data-paddingright="[0,0,0,0]"
                                 data-paddingtop="[0,0,0,0]"
                                 data-responsive_offset="on"
                                 data-type="shape"
                                 data-height="auto"
                                 data-whitespace="nowrap"
                                 data-width="none"
                                 data-hoffset="['-80','15','15','15']"
                                 data-voffset="['0','0','0','0']"
                                 data-x="['right','right','right','right']"
                                 data-y="['bottom','bottom','bottom','bottom']"
                                 data-frames='[{"from":"x:[100%];z:0;rX:0deg;rY:0;rZ:0;sX:1;sY:1;skX:0;skY:0;","mask":"x:0px;y:0px;s:inherit;e:inherit;","speed":1000,"to":"o:1;","delay":1000,"ease":"Power3.easeInOut"},{"delay":"wait","speed":1000,"to":"auto:auto;","mask":"x:0;y:0;s:inherit;e:inherit;","ease":"Power3.easeInOut"}]'>
                                <figure class="content-image"><img src="<?php echo $path; ?>images/main-slider/content-image-3.png" alt=""></figure>
                            </div>

                        </li>

                    </ul>
                </div>
            </div>
        </section>
        <!--End Main Slider-->

        <!--Featured Section-->
        <section class="featured-section">
            <div class="auto-container">
                <div class="inner-container clearfix">

                    <!--Featured Block-->
                    <div class="featured-block col-md-4 col-sm-6 col-xs-12">
                        <div class="inner-box">
                            <div class="lower-box">
                                <div class="lower-inner">
                                    <div class="icon-box">
                                        <span class="icon"><img src="<?php echo $path; ?>images/icons/featured-icon-1.png" alt="" /></span>
                                    </div>
                                    <h3>Advanced SEO Consultant</h3>
                                    <div class="title">Big Business, Big Needs</div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <!--Featured Block-->
                    <div class="featured-block col-md-4 col-sm-6 col-xs-12">
                        <div class="inner-box">
                            <div class="lower-box">
                                <div class="lower-inner">
                                    <div class="icon-box">
                                        <span class="icon"><img src="<?php echo $path; ?>images/icons/featured-icon-2.png" alt="" /></span>
                                    </div>
                                    <h3>Keyword & Market Research</h3>
                                    <div class="title">Heart Of Search Engine</div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <!--Featured Block-->
                    <div class="featured-block col-md-4 col-sm-6 col-xs-12">
                        <div class="inner-box">
                            <div class="lower-box">
                                <div class="lower-inner">
                                    <div class="icon-box">
                                        <span class="icon"><img src="<?php echo $path; ?>images/icons/featured-icon-3.png" alt="" /></span>
                                    </div>
                                    <h3>Website Analysis/Audit </h3>
                                    <div class="title">Monitoring Website Health</div>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </section>
        <!--End Featured Section-->

        <!--Featured Section Two-->
        <section class="featured-section-two" style="background-image:url(images/background/pattern-2.png)">
            <div class="auto-container">
                <!--Sec Title-->
                <div class="sec-title centered">
                    <h2>Socicos Focus</h2>
                </div>
                <div class="inner-container">
                    <div class="clearfix">

                        <!--Featured Block Two-->
                        <div class="featured-block-two col-md-4 col-sm-6 col-xs-12">
                            <div class="inner-box">
                                <div class="icon-box">
                                    <span class="icon"><img src="<?php echo $path; ?>images/icons/featured-icon-4.png" alt="" /></span>
                                </div>
                                <h3>Social Media Management</h3>
                                <div class="text"></div>
                            </div>
                        </div>

                        <!--Featured Block Two-->
                        <div class="featured-block-two col-md-4 col-sm-6 col-xs-12">
                            <div class="inner-box">
                                <div class="icon-box">
                                    <span class="icon"><img src="<?php echo $path; ?>images/icons/featured-icon-5.png" alt="" /></span>
                                </div>
                                <h3>Social Media Analytics</h3>
                                <div class="text"></div>
                            </div>
                        </div>

                        <!--Featured Block Two-->
                        <div class="featured-block-two col-md-4 col-sm-6 col-xs-12">
                            <div class="inner-box">
                                <div class="icon-box">
                                    <span class="icon"><img src="<?php echo $path; ?>images/icons/featured-icon-6.png" alt="" /></span>
                                </div>
                                <h3>Social Media Automation</h3>
                                <div class="text"></div>
                            </div>
                        </div>

                        <!--Featured Block Two-->
                        <div class="featured-block-two col-md-4 col-sm-6 col-xs-12">
                            <div class="inner-box">
                                <div class="icon-box">
                                    <span class="icon"><img src="<?php echo $path; ?>images/icons/featured-icon-7.png" alt="" /></span>
                                </div>
                                <h3>Social Media Ad Affiliation</h3>
                                <div class="text"></div>
                            </div>
                        </div>

                        <!--Featured Block Two-->
                        <div class="featured-block-two col-md-4 col-sm-6 col-xs-12">
                            <div class="inner-box">
                                <div class="icon-box">
                                    <span class="icon"><img src="<?php echo $path; ?>images/icons/featured-icon-8.png" alt="" /></span>
                                </div>
                                <h3>Landing Page Creator</h3>
                                <div class="text"></div>
                            </div>
                        </div>

                        <!--Featured Block Two-->
                        <div class="featured-block-two col-md-4 col-sm-6 col-xs-12">
                            <div class="inner-box">
                                <div class="icon-box">
                                    <span class="icon"><img src="<?php echo $path; ?>images/icons/featured-icon-9.png" alt="" /></span>
                                </div>
                                <h3>Website Traffic</h3>
                                <div class="text"></div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
        </section>
        <!--End Featured Section Two-->


        <!--Score Section-->
        <section class="score-section" style="background-image:url(<?php echo $path; ?>images/background/1.jpg)">
            <div class="auto-container">
                <!--Upper Box-->
                <div class="upper-box">
                    <div class="row clearfix">
                        <!--Title Column-->
                        <div class="title-column col-md-8 col-sm-12 col-xs-12">
                            <div class="sec-title light">
                                <h2>Subscribe For Socicos Offer</h2>
                            </div>
                        </div>
                        <!--Text Column-->
                        <div class="text-column col-md-8 col-sm-12 col-xs-12">
                            <!--<div class="text">You deserve to know your SEO Score because health of website is the health of your wealth.</div>-->
                        </div>
                    </div>
                </div>

                <!--Lower Box-->
                <div class="lower-box">
                    <div class="row clearfix">

                        <!--Form Column-->
                        <div class="form-column col-md-7 col-sm-12 col-xs-12">
                            <div class="inner-column">
                                <div class="row clearfix">
                                    <!--Form Box-->
                                    <div class="form-box col-md-6 col-sm-12 col-xs-12">
                                        <!--Score Form-->
                                        <div class="score-form">
                                            <form method="post" action="<?php echo $path; ?>Home/insertseoscore" id="seoscore" name="seoscore" enctype="multipart/form-data">
                                                <div class="form-group">
                                                    <input type="text" name="url" id="url" placeholder="Your Website URL" required>
                                                </div>
                                                <div class="form-group">
                                                    <input type="email" name="seoscore_email" id="seoscore_email" placeholder="Email Address" required>
                                                </div>
                                                <div class="form-group">
                                                    <button type="submit" class="theme-btn btn-style-one">Get Offer</button>
                                                </div>
                                            </form>
                                        </div>
                                        <!--End Score Form-->
                                    </div>
                                    <!--Progress Box-->
                                    <div class="progress-column col-md-6 col-sm-12 col-xs-12">
                                        <div class="img-responsive">
                                            <img src="<?php echo $path; ?>images/download.png" style="height: 170px; margin-top: 30px; margin-left: 40px;">
                                        </div>
                                        <!-- <div class="inner">
                                             <input type="text" class="dial" data-fgColor="rgba(255,255,255,0);" data-bgColor="rgba(255,255,255,0.10)" data-width="160" data-height="160" data-linecap="normal"  value="78">
                                             <div class="inner-text count-box"><span class="count-text txt" data-stop="78" data-speed="2000"></span> %</div>
                                         </div>
                                         <a target="_blank" href="http://app.socicos.com/" class="contact">Login to Improve</a>-->
                                    </div>
                                </div>
                            </div>
                        </div>
                        <!--Video Column-->
                        <div class="video-column col-md-5 col-sm-12 col-xs-12">
                            <!--Video Box-->
                            <div class="video-box">
                                <figure class="image">
                                    <img src="<?php echo $path; ?>images/FileDownload.jpg" alt="">
                                    <!--<a href="https://www.youtube.com/watch?v=kxPCFljwJws" class="lightbox-image overlay-box"><span class="icon"></span></a>-->
                                </figure>
                                <h3>How It’s Work</h3>
                            </div>
                        </div>

                    </div>
                </div>

            </div>
        </section>
        <!--End Score Section-->

        <!--Services Section-->
        <section class="services-section">
            <div class="auto-container">
                <!--Sec Title-->
                <div class="sec-title centered">
                    <h2>Digital Marketing Knowledgebase</h2>
                    <div class="text">91% of internet users are not willing to leave the first page. </p> If you are not first then you are last.</div>
                </div>

                <div class="three-item-carousel owl-carousel owl-theme">

                    <!--Services Block-->
                    <div class="services-block">
                        <div class="inner-box">
                            <div class="icon-box">
                                <span class="icon"><img src="<?php echo $path; ?>images/icons/services-1.png" alt="" /></span>
                            </div>
                            <h3>Search Engine Optimization</h3>
                            <div class="text">Optimizing your web pages according to search engine guidelines is called SEO. Optimization...</div>

                        </div>
                    </div>

                    <!--Services Block-->
                    <div class="services-block">
                        <div class="inner-box">
                            <div class="icon-box">
                                <span class="icon"><img src="<?php echo $path; ?>images/icons/services-2.png" alt="" /></span>
                            </div>
                            <h3><a href="<?php echo $path; ?>Management/socialmediamanagement">Social Media Management</a></h3>
                            <div class="text">A capable instrument for correspondence, online networking enables organizations...</div>
                            <a href="<?php echo Mage::getBaseUrl(); ?>socialmediamanagement" class="read-more"><span class="icon flaticon-right-arrow-1"></span> Read More</a>
                        </div>
                    </div>

                    <!--Services Block-->
                    <div class="services-block">
                        <div class="inner-box">
                            <div class="icon-box">
                                <span class="icon"><img src="<?php echo $path; ?>images/icons/services-3.png" alt="" /></span>
                            </div>
                            <h3><a href="<?php echo $path; ?>Management/mobilemarketing">Mobile Web Marketing</a></h3>
                            <div class="text">People on Mobile are very distracted or they display a distracted form of behaviour meaning...</div>
                            <a href="<?php echo Mage::getBaseUrl(); ?>mobilemarketing" class="read-more"><span class="icon flaticon-right-arrow-1"></span> Read More</a>
                        </div>
                    </div>

                    <!--Services Block-->
                    <div class="services-block">
                        <div class="inner-box">
                            <div class="icon-box">
                                <span class="icon"><img src="<?php echo $path; ?>images/icons/services-1.png" alt="" /></span>
                            </div>
                            <h3>Directory Submission List</h3>
                            <div class="text"></div>

                        </div>
                    </div>

                    <!--Services Block-->
                    <div class="services-block">
                        <div class="inner-box">
                            <div class="icon-box">
                                <span class="icon"><img src="<?php echo $path; ?>images/icons/services-2.png" alt="" /></span>
                            </div>
                            <h3>Wordpress Installation</h3>
                            <div class="text"></div>

                        </div>
                    </div>

                    <!--Services Block-->
                    <div class="services-block">
                        <div class="inner-box">
                            <div class="icon-box">
                                <span class="icon"><img src="<?php echo $path; ?>images/icons/services-3.png" alt="" /></span>
                            </div>
                            <h3><a href="<?php echo $path; ?>Management/contentmarketing">Connect Marketing</a></h3>
                            <div class="text">Content Marketing means creating and sharing valuable free content to attract...</div>
                            <a href="<?php echo Mage::getBaseUrl(); ?>contentmarketing" class="read-more"><span class="icon flaticon-right-arrow-1"></span> Read More</a>
                        </div>
                    </div>

                </div>

            </div>
        </section>
        <!--End Services Section-->

        <!--Marketing Section-->
        <section class="marketing-section">
            <div class="auto-container">
                <div class="row clearfix">

                    <!--Image Column-->
                    <div class="image-column col-md-6 col-sm-12 col-xs-12">
                        <div class="image" style="margin-top:80px;">
                            <img src="<?php echo $path; ?>images/resource/marketing.jpeg" alt="" />
                        </div>
                    </div>
                    <!--Content Column-->
                    <div class="content-column col-md-6 col-sm-12 col-xs-12">
                        <div class="inner-column">
                            <h2>How SOCICOS helps you in website marketing for your business magnification.</h2>
                            <div class="single-item-carousel owl-carousel owl-theme">

                                <!--Market Content-->
                                <div class="market-content">
                                    <div class="content-inner">
                                        <div class="content-number">1.</div>
                                        <h3>Search Engine Optimization Audit</h3>
                                        <div class="text">It take hours, not day, week or month to audit your website. Get in depth analytics about your website in one click</div>

                                        <div class="featured-block-three">
                                            <div class="featured-inner">
                                                <div class="icon-box">
                                                    <span class="icon"><img src="<?php echo $path; ?>images/icons/featured-icon-10.png" alt="" /></span>
                                                </div>
                                                <h4>Competitive Heath Report</h4>
                                                <div class="featured-text">Competitor analysis report with statistic</div>
                                            </div>
                                        </div>

                                        <div class="featured-block-three">
                                            <div class="featured-inner">
                                                <div class="icon-box">
                                                    <span class="icon"><img src="<?php echo $path; ?>images/icons/featured-icon-11.png" alt="" /></span>
                                                </div>
                                                <h4>Traffic Analysis</h4>
                                                <div class="featured-text">Live Web Traffic Analysis and Visitors Details</div>
                                            </div>
                                        </div>

                                    </div>
                                </div>

                                <!--Market Content-->
                                <div class="market-content">
                                    <div class="content-inner">
                                        <div class="content-number">2.</div>
                                        <h3>Search Engine Result Page Aduit</h3>
                                        <div class="text">How all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of system, the actual teachings of the great explorer.</div>

                                        <div class="featured-block-three">
                                            <div class="featured-inner">
                                                <div class="icon-box">
                                                    <span class="icon"><img src="<?php echo $path; ?>images/icons/featured-icon-10.png" alt="" /></span>
                                                </div>
                                                <h4>Search Engine Reporting</h4>
                                                <div class="featured-text">The best strategy to improve your ranking</div>
                                            </div>
                                        </div>

                                        <div class="featured-block-three">
                                            <div class="featured-inner">
                                                <div class="icon-box">
                                                    <span class="icon"><img src="<?php echo $path; ?>images/icons/featured-icon-11.png" alt="" /></span>
                                                </div>
                                                <h4>Keyword Analysis</h4>
                                                <div class="featured-text">Find the best Keyword for your landing page.</div>
                                            </div>
                                        </div>

                                    </div>
                                </div>

                                <!--Market Content-->
                                <div class="market-content">
                                    <div class="content-inner">
                                        <div class="content-number">3.</div>
                                        <h3>Social Media Audit</h3>
                                        <div class="text">How all this mistaken idea of denouncing pleasure and praising pain was born and I will give you a complete account of system, the actual teachings of the great explorer.</div>

                                        <div class="featured-block-three">
                                            <div class="featured-inner">
                                                <div class="icon-box">
                                                    <span class="icon"><img src="<?php echo $path; ?>images/icons/featured-icon-10.png" alt="" /></span>
                                                </div>
                                                <h4>Social Score</h4>
                                                <div class="featured-text">Know your website or landing page shares on Social Networks</div>
                                            </div>
                                        </div>

                                        <div class="featured-block-three">
                                            <div class="featured-inner">
                                                <div class="icon-box">
                                                    <span class="icon"><img src="<?php echo $path; ?>images/icons/featured-icon-11.png" alt="" /></span>
                                                </div>
                                                <h4>Social Analytics</h4>
                                                <div class="featured-text">Complete Social post Analysis</div>
                                            </div>
                                        </div>

                                    </div>
                                </div>

                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </section>
        <!--End Marketing Section-->

        <!--Testimonial Section-->
        <section class="testimonial-section" style="background-image:url(images/background/2.jpg)">
            <div class="auto-container">
                <div class="row clearfix">

                    <!--Title Column-->
                    <div class="title-column col-md-5 col-sm-12 col-xs-12">
                        <div class="inner-column">
                            <h2>Words <br> From Our Trusted <br> Customers.</h2>
                        </div>
                    </div>
                    <!--Testimonial Column-->
                    <div class="testimonial-column col-md-7 col-sm-12 col-xs-12">
                        <div class="testimonial-carousel owl-carousel owl-theme">

                            <!--Testimonial Block-->
                            <div class="testimonial-block">
                                <div class="inner-box">
                                    <div class="quote-icon">
                                        <span class="icon flaticon-straight-quotes"></span>
                                    </div>
                                    <div class="text">We have been using Socicos tool for four months now. The automation tool is excellent that reduces my time on analysis & reporting. Most importantly we are seeing a rapid growth in our traffic. We recommend this tool for saving your time and focusing on additional goals in the business.</div>
                                    <a href="#" class="continue"><span class="icon flaticon-right-arrow-1"></span> Continue to Read</a>
                                    <div class="author-info">
                                        <div class="author-inner">
                                            <div class="image"><img src="<?php echo $path; ?>images/resource/author-1.png" alt="" /></div>
                                            <h3>Rupa Mehta</h3>
                                            <div class="designation">CEO/Founder, Mehta Enterprise</div>
                                        </div>

                                    </div>
                                </div>
                            </div>

                            <!--Testimonial Block-->
                            <div class="testimonial-block">
                                <div class="inner-box">
                                    <div class="quote-icon">
                                        <span class="icon flaticon-straight-quotes"></span>
                                    </div>
                                    <div class="text">Socicos is the best tool as I believe that the delivery and strategy of the reports are giving the best idea to rank higher on search engines. Moreover, the uniqueness of this tool is 'Reminders' on corrections on the scheduled date and time. I highly recommend to the Bloggers and Website owners. </div>
                                    <a href="#" class="continue"><span class="icon flaticon-right-arrow-1"></span> Continue to Read</a>
                                    <div class="author-info">
                                        <div class="author-inner">
                                            <div class="image"><img src="<?php echo $path; ?>images/resource/author-1.png" alt="" /></div>
                                            <h3>Mrs. Eva Mcoy</h3>
                                            <div class="designation">Marketing Analyst</div>
                                        </div>

                                    </div>
                                </div>
                            </div>

                            <!--Testimonial Block-->

                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!--End Testimonial Section-->

        <!--Price Section-->
        <section class="price-section">
            <div class="auto-container">
                <!--Sec Title-->
                <div class="sec-title centered">
                    <h2>Pricing Plans</h2>
                    <div class="text">You are free to use now and get the benefits of waving one year subscription.</br></br></div>
                    <div class="form-group">
                        <a target="_blank" href="http://app.socicos.com/Socialregistration"> <button class="theme-btn btn-style-one">Sign Up Now</button></a>
                    </div>
                </div>
            </div>
        </section>
        <!--End Price Section-->

        <!--Partners Section-->
        <?php echo $this->getLayout()->createBlock('core/template')->setTemplate('catalog/product/partners.phtml')->toHtml(); ?>
        <!--End Partners Section-->

        <!--Main Footer-->
        <?php echo $this->getLayout()->createBlock('core/template')->setTemplate('catalog/product/footer.phtml')->toHtml(); ?>
        <!--Main Footer-->
        <!--Bottom Parallax-->
        <div class="bottom-parallax">
            <!--About Section-->
            <section class="about-section" style="background-image:url(<?php echo $path; ?>images/background/pattern-3.png)">
                <div class="auto-container">
                    <div class="inner">
                        <h2>We don’t just talk about what is coming next, we do it.</h2>
                        <a target="_blank" href="<?php echo Mage::getUrl('customer/account/create'); ?>" class="theme-btn btn-style-three">Join With Us</a>
                    </div>
                </div>
            </section>
            <!--End About Section-->
        </div>

    </div>
    <!--End pagewrapper-->

    <!--Scroll to top-->
    <div class="scroll-to-top scroll-to-target" data-target="html"><span class="icon fa fa-angle-double-up"></span></div>

    <script src="<?php echo $path; ?>js/jquery.js"></script>
    <!--Revolution Slider-->
    <script src="<?php echo $path; ?>assets/revolution/js/jquery.themepunch.revolution.min.js"></script>
    <script src="<?php echo $path; ?>assets/revolution/js/jquery.themepunch.tools.min.js"></script>
    <script src="<?php echo $path; ?>assets/revolution/js/extensions/revolution.extension.actions.min.js"></script>
    <script src="<?php echo $path; ?>assets/revolution/js/extensions/revolution.extension.carousel.min.js"></script>
    <script src="<?php echo $path; ?>assets/revolution/js/extensions/revolution.extension.kenburn.min.js"></script>
    <script src="<?php echo $path; ?>assets/revolution/js/extensions/revolution.extension.layeranimation.min.js"></script>
    <script src="<?php echo $path; ?>assets/revolution/js/extensions/revolution.extension.migration.min.js"></script>
    <script src="<?php echo $path; ?>assets/revolution/js/extensions/revolution.extension.navigation.min.js"></script>
    <script src="<?php echo $path; ?>assets/revolution/js/extensions/revolution.extension.parallax.min.js"></script>
    <script src="<?php echo $path; ?>assets/revolution/js/extensions/revolution.extension.slideanims.min.js"></script>
    <script src="<?php echo $path; ?>assets/revolution/js/extensions/revolution.extension.video.min.js"></script>
    <script src="<?php echo $path; ?>js/main-slider-script.js"></script>

    <script src="<?php echo $path; ?>js/bootstrap.min.js"></script>
    <script src="<?php echo $path; ?>js/jquery.fancybox.pack.js"></script>
    <script src="<?php echo $path; ?>js/jquery.fancybox-media.js"></script>
    <script src="<?php echo $path; ?>js/owl.js"></script>
    <script src="<?php echo $path; ?>js/wow.js"></script>
    <script src="<?php echo $path; ?>js/knob.js"></script>
    <script src="<?php echo $path; ?>js/appear.js"></script>
    <script src="<?php echo $path; ?>js/script.js"></script>
</body>
</html>