<?php $path = Mage::getBaseUrl( Mage_Core_Model_Store::URL_TYPE_WEB, true ) . 'socicos/'; ?>
<footer class="main-footer">
    <div class="auto-container">

        <!--Widgets Section-->
        <div class="widgets-section">
            <div class="row clearfix">

                <!--Column-->
                <div class="column col-md-4 col-sm-6 col-xs-12">
                    <div class="footer-widget links-widget">
                        <div class="footer-title">
                            <h2>Usefull Links</h2>
                        </div>
                        <div class="widget-content">
                            <div class="row clearfix">
                                <div class="widget-column col-md-6 col-sm-6 col-xs-12">
                                    <ul class="footer-list">
                                        <li><a href="<?php echo Mage::getBaseUrl(); ?>">Home</a></li>
                                        <li><a href="<?php echo Mage::getBaseUrl(); ?>about-us">About Us</a></li>
                                        <li><a href="<?php echo Mage::getBaseUrl(); ?>tools">Tools</a></li>
                                        <li><a href="<?php echo Mage::getBaseUrl(); ?>howitworks">How it Works?</a></li>
                                        <li><a href="<?php echo Mage::getBaseUrl(); ?>management">Resources</a></li>
                                        <li><a href="<?php echo Mage::getBaseUrl(); ?>contactus">Contact Us</a></li>
                                    </ul>
                                </div>
                                <div class="widget-column col-md-6 col-sm-6 col-xs-12">
                                    <ul class="footer-list">
                                        <li><a target="_blank" href="<?php echo Mage::getUrl('customer/account/login'); ?>">Login</a></li>
                                        <li><a target="_blank" href="<?php echo Mage::getUrl('customer/account/create'); ?>">Register</a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <!--Column-->
                <div class="column col-md-4 col-sm-6 col-xs-12">
                    <div class="footer-widget subscribe-widget">
                        <div class="footer-title">
                            <h2>Subscribe Us</h2>
                        </div>
                        <div class="widget-content">
                            <div class="text">Subscribe us for recieve latest Updates <br> News and Offers.</div>
                            <div class="subscribe-form">
                                <form method="post" action="<?php echo $path; ?>Home/insertsubscribe" id="subscribe" name="subscribe" enctype="multipart/form-data">
                                    <div class="form-group">
                                        <input type="email" name="subscribe_email" id="subscribe_email" placeholder="Email Address..." required="">
                                        <button type="submit" class="theme-btn"><span class="flaticon-right-arrow-1"></span></button>
                                    </div>
                                </form>
                            </div>
                            <ul class="social-icon-one">
                                <li><a href="#"><span class="fa fa-facebook-f"></span></a></li>
                                <li><a href="#"><span class="fa fa-twitter"></span></a></li>
                                <li><a href="#"><span class="fa fa-linkedin"></span></a></li>
                                <li><a href="#"><span class="fa fa-rss"></span></a></li>
                                <li><a href="#"><span class="fa fa-google-plus"></span></a></li>
                                <li><a href="#"><span class="fa fa-vimeo"></span></a></li>
                            </ul>
                        </div>
                    </div>
                </div>

                <!--Column-->
                <div class="column col-md-4 col-sm-6 col-xs-12">
                    <div class="footer-widget office-widget">
                        <div class="footer-title">
                            <h2>Corporate Office</h2>
                        </div>
                        <div class="widget-content">
                            <div class="single-item-carousel owl-carousel owl-theme">

                                <div class="office-info">
                                    <ul>
                                        <li><strong>Address:</strong></li>
                                        <li>3rd Floor, SuryaPrema
                                            #15, Plot No 1 & 2, 1st Cross, Manjunathanagar, Kanakpura Road, Bengaluru, Karnataka 560062</li>
                                        <li><a href="#">Find Us On Map</a></li>
                                    </ul>
                                </div>

                                <div class="office-info">
                                    <ul>
                                        <li><strong>Address:</strong></li>
                                        <li>3rd Floor, SuryaPrema
                                            #15, Plot No 1 & 2, 1st Cross, Manjunathanagar, Kanakpura Road, Bengaluru, Karnataka 560062 </li>
                                        <li><a href="#">Find Us On Map</a></li>
                                    </ul>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>

    </div>
    <!--Copyright-->
    <div class="copyright">Copyright &copy; 2012-2018 SOCICOS. All rights reserved.</div>
</footer>