<?php $path = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB, true) . 'socicos/'; ?>
<head>
    <meta charset="utf-8">
    <title>Digital Marketing & Analytics Tools | Socicos</title>
    <link href="<?php echo $path; ?>css/bootstrap.css" rel="stylesheet">
    <link href="<?php echo $path; ?>assets/revolution/css/settings.css" rel="stylesheet" type="text/css"><!-- REVOLUTION SETTINGS STYLES -->
    <link href="<?php echo $path; ?>assets/revolution/css/layers.css" rel="stylesheet" type="text/css"><!-- REVOLUTION LAYERS STYLES -->
    <link href="<?php echo $path; ?>assets/revolution/css/navigation.css" rel="stylesheet" type="text/css"><!-- REVOLUTION NAVIGATION STYLES -->
    <link href="<?php echo $path; ?>css/style.css" rel="stylesheet">
    <link href="<?php echo $path; ?>css/responsive.css" rel="stylesheet">
    <link rel="shortcut icon" href="<?php echo $path; ?>images/FileDownload1.png" type="image/x-icon">
    <link rel="icon" href="<?php echo $path; ?>images/FileDownload1.png" type="image/x-icon">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
    <!--[if lt IE 9]><script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.js"></script><![endif]-->
    <!--[if lt IE 9]><script src="<?php echo $path; ?>js/respond.js"></script><![endif]-->
</head>
