<?php $path = Mage::getBaseUrl( Mage_Core_Model_Store::URL_TYPE_WEB, true ) . 'socicos/'; ?>
<header class="main-header header-style-two">
    <!-- Header Top -->
    <div class="header-top">
        <div class="auto-container">
            <div class="top-outer clearfix">
                <!--Top Left-->
                <div class="top-left">
                    <ul class="links clearfix">
                        <li><a href = "mailto:help@socicos.com" target="_top"><span class="icon fa fa-envelope"></span><strong>help@socicos.com</strong> </a></li>
                        <li><a href="<?php echo Mage::getBaseUrl(); ?>contactus"><span class="icon"></span>Contact Us</a></li>
                    </ul>
                </div>

                <!--Top Right-->
                <div class="top-right clearfix">
                    <ul class="clearfix">
                       <!-- <li><a href="#"><span class="icon flaticon-planet-earth"></span>Free SEO Analysis</a></li>-->
                        <li>
                            <a target="_blank" href="<?php echo Mage::getUrl('customer/account/login'); ?>">
                                <span class="icon flaticon-user"></span>Login
                            </a> 
                            <span>or</span> 
                            <a target="_blank" href="<?php echo Mage::getUrl('customer/account/create'); ?>">
                                <span class="icon flaticon-upload"></span>Register
                            </a>
                        </li>
                    </ul>
                </div>

            </div>

        </div>
    </div>
    <!-- Header Top End -->

    <!-- Main Box -->
    <div class="main-box">
        <div class="auto-container">
            <div class="outer-container clearfix">
                <!--Logo Box-->
                <div class="logo-box">
                    <div class="logo"><a href="<?php echo Mage::getBaseUrl(); ?>"><img src="<?php echo $path; ?>images/logo-small.png" alt=""></a></div>
                </div>

                <!--Nav Outer-->
                <div class="nav-outer clearfix">

                    <!-- Main Menu -->
                    <nav class="main-menu">
                        <div class="navbar-header">
                            <!-- Toggle Button -->
                            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>
                        </div>

                        <div class="navbar-collapse collapse clearfix">
                            <ul class="navigation clearfix">
                                <li><a href="<?php echo Mage::getBaseUrl(); ?>">Home</a></li>
                                <li><a href="<?php echo Mage::getBaseUrl(); ?>about-us">About Us</a></li>
                                <li><a href="<?php echo Mage::getBaseUrl(); ?>tools">Tools</a></li>
                                <li><a href="<?php echo Mage::getBaseUrl(); ?>howitworks">How it Works?</a></li>
                                <li><a href="<?php echo Mage::getBaseUrl(); ?>management">Resources</a></li>
                                <li><a href="<?php echo Mage::getBaseUrl(); ?>contactus">Contact Us</a></li>
                            </ul>
                        </div>
                    </nav>

                </div>
                <!--Nav Outer End-->

            </div>
        </div>
    </div>

    <!--Sticky Header-->
    <div class="sticky-header">
        <div class="auto-container">

            <div class="outer-container clearfix">
                <!--Logo Box-->
                <div class="logo-box pull-left">
                    <div class="logo"><a href="<?php echo Mage::getBaseUrl(); ?>"><img src="<?php echo $path; ?>images/logo-small.png" alt=""></a></div>
                </div>

                <!--Nav Outer-->
                <div class="nav-outer clearfix">
                    <!-- Main Menu -->
                    <nav class="main-menu">
                        <div class="navbar-header">
                            <!-- Toggle Button -->
                            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>
                        </div>

                        <div class="navbar-collapse collapse clearfix">
                            <ul class="navigation clearfix">
                                <li><a href="<?php echo Mage::getBaseUrl(); ?>">Home</a></li>
                                <li><a href="<?php echo Mage::getBaseUrl(); ?>about-us">About Us</a></li>
                                <li><a href="<?php echo Mage::getBaseUrl(); ?>tools">Tools</a></li>
                                <li><a href="<?php echo Mage::getBaseUrl(); ?>howitworks">How it Works?</a></li>
                                <li><a href="<?php echo Mage::getBaseUrl(); ?>management">Resources</a></li>
                                <li><a href="<?php echo Mage::getBaseUrl(); ?>contactus">Contact Us</a></li>
                            </ul>
                        </div>
                    </nav>
                    <!-- Main Menu End-->
                </div>
                <!--Nav Outer End-->
            </div>
        </div>
    </div>
    <!--End Sticky Header-->
</header>
