<?php $path = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB, true) . 'socicos/'; ?>
<div class="header-top">
    <div class="auto-container">
        <div class="clearfix">
            <!--Top Left-->
            <div class="top-left">
                <ul class="links clearfix">
                    <li><a href = "mailto:help@socicos.com" target="_top"><span class="icon fa fa-envelope"></span><strong>help@socicos.com</strong> </a></li>
                    <li><a href="<?php echo Mage::getBaseUrl(); ?>contactus"><span class="icon"></span>Contact Us</a></li>
                </ul>
            </div>

            <!--Top Right-->
            <div class="top-right clearfix">
                <ul class="clearfix">
                    <li>
                        <a target="_blank" href="<?php echo Mage::getUrl('customer/account/login'); ?>">
                            <span class="icon flaticon-user"></span>Login
                        </a> 
                        <span>or</span> 
                        <a target="_blank" href="<?php echo Mage::getUrl('customer/account/create'); ?>">
                            <span class="icon flaticon-upload"></span>Register
                        </a>
                    </li>
                </ul>
            </div>
            </li>
            </ul>
        </div>

    </div>

</div>
