<!DOCTYPE html>
<html>
<?php echo $this->getLayout()->createBlock('core/template')->setTemplate('catalog/product/head.phtml')->toHtml(); ?>
<body>
<header class="main-header header-style-five">

    <!-- Header Top -->
    <?php echo $this->getLayout()->createBlock('core/template')->setTemplate('catalog/product/header_top.phtml')->toHtml(); ?>
    </div>
    <!-- Header Top End -->

    <!-- Main Box -->
    <div class="main-box">
        <div class="auto-container">
            <div class="outer-container clearfix">
                <!--Logo Box-->
                <?php echo $this->getLayout()->createBlock('core/template')->setTemplate('catalog/product/logo.phtml')->toHtml(); ?>
                <!--Nav Outer-->
                <div class="nav-outer clearfix">

                    <!-- Main Menu -->
                    <nav class="main-menu">
                        <div class="navbar-header">
                            <!-- Toggle Button -->
                            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>
                        </div>

                        <div class="navbar-collapse collapse clearfix">
                            <?php echo $this->getLayout()->createBlock('core/template')->setTemplate('catalog/product/top_navigation1.phtml')->toHtml(); ?>
                        </div>
                    </nav>
                    <!-- Main Menu End-->
                </div>
                <!--Nav Outer End-->

            </div>
        </div>
    </div>

    <!--Sticky Header-->
    <div class="sticky-header">
        <div class="auto-container">

            <div class="outer-container clearfix">
                <!--Logo Box-->
                <div class="logo-box pull-left">
                    <div class="logo"><a href="https://www.socicos.com/Home"><img src="https://www.socicos.com/images/logo-small.png" alt=""></a></div>
                </div>

                <!--Nav Outer-->
                <div class="nav-outer clearfix">
                    <!-- Main Menu -->
                    <nav class="main-menu">
                        <div class="navbar-header">
                            <!-- Toggle Button -->
                            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>
                        </div>

                        <div class="navbar-collapse collapse clearfix">
                            <?php echo $this->getLayout()->createBlock('core/template')->setTemplate('catalog/product/top_navigation2.phtml')->toHtml(); ?>
                        </div>
                    </nav>
                    <!-- Main Menu End-->

                </div>
                <!--Nav Outer End-->

            </div>

        </div>
    </div>
    <!--End Sticky Header-->

</header>
<!--End Main Header --><style>
    table {
        font-family: arial, sans-serif;
        border-collapse: collapse;
        width: 80%;
    }

    td, th {
        border: 1px solid #dddddd;
        text-align: left;
        padding: 8px;
    }
</style>
<!--Page Title-->
<section class="page-title" style="background-image:url(images/background/pattern-4.png);">
    <div class="auto-container">
        <h1>LEAD GENERATION</h1>
    </div>
    <!--Page Info-->
    <div class="page-info">
        <div class="auto-container">
            <div class="inner-container">
                <ul class="bread-crumb">
                    <li><a href="https://www.socicos.com/Home">Home</a></li>
                    <li>LEAD GENERATION</li>
                </ul>
            </div>
        </div>
    </div>
    <!--End Page Info-->
</section>

<div class="sidebar-page-container">
    <div class="auto-container">
        <div class="row clearfix">

            <!--Content Side-->
            <div class="content-side col-lg-8 col-md-8 col-sm-12 col-xs-12">
                <!--Our Single-->
                <div class="blog-single">
                    <div class="inner-box">
                        <h2>LEAD GENERATION</h2>

                        <div class="lower-content">
                            <div class="text">
                                <h3>What is lead generation?</h3>
                                <p class="text-left">Lead generation is the first step to gain consumer interest or enquiry into products or services of a business. Leads can be generated for a purpose such as list building, e-news letter list, acquisition, competitors list, etc. Leads can be collected from various sources, For Example: Digitally via Internet, through personal referrals, telephonic calls, through advertisements or events or sponsorship programs.</p>
                                <p class="text-left">There are three types of leads in lead generation<br>
                                    1.	Sales Leads: Sales leads are generated on the basis of demographic criteria such as income, age, household income, interest basis, etc. Sales leads are followed up through phone calls, emails, SMS, etc.  by the sales force.<br>
                                    2.	Marketing Leads: marketing leads are brand-specific leads generated for unique offer advertisement. These leads are basically for visibility in the market & gaining attention of the public by showing amazing offers of any business/ Product/ Services. For Example: Get 25% OFF on your first purchase with us. Get upto 20% cashback on every purchase you do with us.<br>
                                    3.	Affiliate Leads: Affiliate leads give you extreme no. of public both interested and not interested. They fill up the form or sign up for a benefit of getting something in return which gives you a option of trail on the user to gain back something by selling your product or services.<br>
                                </p>
                                <p>Lead Generation Tools For A Business:<br><br>
                                <table style="color: black">
                                    <tr>
                                        <td>1</td>
                                        <td>Offline Advertisement</td>
                                    </tr>
                                    <tr>
                                        <td>2</td>
                                        <td>Email </td>
                                    </tr>
                                    <tr>
                                        <td>3</td>
                                        <td>Self Owned Websites</td>
                                    </tr>
                                    <tr>
                                        <td>4</td>
                                        <td>Social Media</td>
                                    </tr>
                                    <tr>
                                        <td>5</td>
                                        <td>Survey /td>
                                    </tr>
                                    <tr>
                                        <td>6</td>
                                        <td>Referrals</td>
                                    </tr>
                                    <tr>
                                        <td>7</td>
                                        <td>Google Adwords</td>
                                    </tr>
                                    <tr>
                                        <td>8</td>
                                        <td>Directories </td>
                                    </tr>
                                    <tr>
                                        <td>9</td>
                                        <td>Third-Party Advertisements</td>
                                    </tr>
                                    <tr>
                                        <td>10</td>
                                        <td>Buying And Selling Targeted Emails / Mobile No. Database</td>
                                    </tr>
                                    <tr>
                                        <td>11</td>
                                        <td>Affiliate Marketing </td>
                                    </tr>
                                    <tr>
                                        <td>12</td>
                                        <td>Sponsorship Events</td>
                                    </tr>
                                </table>

                                </div>
                            <!--Two Column-->


                            <!--Accordian Boxed-->


                        </div>
                    </div>
                </div>
            </div>

            <!--Sidebar Side-->
            <div class="sidebar-side col-lg-4 col-md-4 col-sm-12 col-xs-12">
                <aside class="sidebar default-sidebar with-border">
                    <!-- Search -->
                    <!--Blog Category Widget-->
                    <!--Recent Comments-->
                    <div class="sidebar-widget recent-comments" style="left: 120px;">
                        <div class="sidebar-title" style="left: 37px;">
                            <h2>Resources</h2>
                        </div>
                        <?php echo $this->getLayout()->createBlock('core/template')->setTemplate('catalog/product/tools_resources.phtml')->toHtml(); ?>
                    </div>
                    <!-- Popular Posts -->
                    <!-- Popular Tags -->
                </aside>
            </div>

        </div>
    </div>
</div></section>
<!--End Partners Section-->

<!--Main Footer-->
<footer class="main-footer">
    <div class="auto-container">

        <!--Widgets Section-->
        <div class="widgets-section">
            <div class="row clearfix">

                <!--Column-->
                <div class="column col-md-4 col-sm-6 col-xs-12">
                    <div class="footer-widget links-widget">
                        <div class="footer-title">
                            <h2>Usefull Links</h2>
                        </div>
                        <div class="widget-content">
                            <div class="row clearfix">
                                <div class="widget-column col-md-6 col-sm-6 col-xs-12">
                                    <ul class="footer-list">
                                        <li><a href="https://www.socicos.com/Home">Home</a></li>
                                        <li><a href="https://www.socicos.com/Aboutus">About Us</a></li>
                                        <li><a href="https://www.socicos.com/Tools">Tools</a></li>
                                        <li><a href="https://www.socicos.com/Howitworks">How it Works?</a></li>
                                        <li><a href="https://www.socicos.com/Management">Resources</a></li>
                                        <li><a href="https://www.socicos.com/Contactus">Contact Us</a></li>
                                    </ul>
                                </div>
                                <div class="widget-column col-md-6 col-sm-6 col-xs-12">
                                    <ul class="footer-list">
                                        <li><a target="_blank" href="http://app.socicos.com/">Login</a></li>
                                        <li><a target="_blank" href="http://app.socicos.com/Socialregistration">Register</a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <!--Column-->
                <div class="column col-md-4 col-sm-6 col-xs-12">
                    <div class="footer-widget subscribe-widget">
                        <div class="footer-title">
                            <h2>Subscribe Us</h2>
                        </div>
                        <div class="widget-content">
                            <div class="text">Subscribe us for recieve latest Updates <br> News and Offers.</div>
                            <div class="subscribe-form">
                                <form method="post" action="contact.html">
                                    <div class="form-group">
                                        <input type="email" name="email" value="" placeholder="Email Address..." required="">
                                        <button type="submit" class="theme-btn"><span class="flaticon-right-arrow-1"></span></button>
                                    </div>
                                </form>
                            </div>
                            <ul class="social-icon-one">
                                <li><a href="#"><span class="fa fa-facebook-f"></span></a></li>
                                <li><a href="#"><span class="fa fa-twitter"></span></a></li>
                                <li><a href="#"><span class="fa fa-linkedin"></span></a></li>
                                <li><a href="#"><span class="fa fa-rss"></span></a></li>
                                <li><a href="#"><span class="fa fa-google-plus"></span></a></li>
                                <li><a href="#"><span class="fa fa-vimeo"></span></a></li>
                            </ul>
                        </div>
                    </div>
                </div>

                <!--Column-->
                <div class="column col-md-4 col-sm-6 col-xs-12">
                    <div class="footer-widget office-widget">
                        <div class="footer-title">
                            <h2>Corporate Office</h2>
                        </div>
                        <div class="widget-content">
                            <div class="single-item-carousel owl-carousel owl-theme">

                                <div class="office-info">
                                    <ul>
                                        <li><strong>Address:</strong></li>
                                        <li>3rd Floor, SuryaPrema
                                            #15, Plot No 1 & 2, 1st Cross, Manjunathanagar, Kanakpura Road, Bengaluru, Karnataka 560062</li>
                                        <li><a href="#">Find Us On Map</a></li>
                                    </ul>
                                </div>

                                <div class="office-info">
                                    <ul>
                                        <li><strong>Address:</strong></li>
                                        <li>3rd Floor, SuryaPrema
                                            #15, Plot No 1 & 2, 1st Cross, Manjunathanagar, Kanakpura Road, Bengaluru, Karnataka 560062 </li>
                                        <li><a href="#">Find Us On Map</a></li>
                                    </ul>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>

    </div>
    <!--Copyright-->
    <div class="copyright">Copyright &copy; 2012-2018 The SOCICOS. All rights reserved.</div>
</footer>
<!--Main Footer-->
<!--Bottom Parallax-->

</div>
<!--End pagewrapper-->

<!--Scroll to top-->
<div class="scroll-to-top scroll-to-target" data-target="html"><span class="icon fa fa-angle-double-up"></span></div>

<script src="https://www.socicos.com/js/jquery.js"></script>
<!--Revolution Slider-->
<script src="https://www.socicos.com/assets/revolution/js/jquery.themepunch.revolution.min.js"></script>
<script src="https://www.socicos.com/assets/revolution/js/jquery.themepunch.tools.min.js"></script>
<script src="https://www.socicos.com/assets/revolution/js/extensions/revolution.extension.actions.min.js"></script>
<script src="https://www.socicos.com/assets/revolution/js/extensions/revolution.extension.carousel.min.js"></script>
<script src="https://www.socicos.com/assets/revolution/js/extensions/revolution.extension.kenburn.min.js"></script>
<script src="https://www.socicos.com/assets/revolution/js/extensions/revolution.extension.layeranimation.min.js"></script>
<script src="https://www.socicos.com/assets/revolution/js/extensions/revolution.extension.migration.min.js"></script>
<script src="https://www.socicos.com/assets/revolution/js/extensions/revolution.extension.navigation.min.js"></script>
<script src="https://www.socicos.com/assets/revolution/js/extensions/revolution.extension.parallax.min.js"></script>
<script src="https://www.socicos.com/assets/revolution/js/extensions/revolution.extension.slideanims.min.js"></script>
<script src="https://www.socicos.com/assets/revolution/js/extensions/revolution.extension.video.min.js"></script>
<script src="https://www.socicos.com/js/main-slider-script.js"></script>

<script src="https://www.socicos.com/js/jquery.js"></script>
<script src="https://www.socicos.com/js/bootstrap.min.js"></script>
<script src="https://www.socicos.com/js/jquery.fancybox.pack.js"></script>
<script src="https://www.socicos.com/js/jquery.fancybox-media.js"></script>
<script src="https://www.socicos.com/js/owl.js"></script>
<script src="https://www.socicos.com/js/wow.js"></script>
<script src="https://www.socicos.com/js/validate.js"></script>
<script src="https://www.socicos.com/js/jquery-ui.js"></script>
<script src="https://www.socicos.com/js/knob.js"></script>
<script src="https://www.socicos.com/js/slick.js"></script>
<script src="https://www.socicos.com/js/appear.js"></script>
<script src="https://www.socicos.com/js/script.js"></script>
<!--<script src="https://www.socicos.com/js/validate.js"></script>-->
<script src="http://maps.google.com/maps/api/js?key=AIzaSyBKS14AnP3HCIVlUpPKtGp7CbYuMtcXE2o"></script>
<script src="https://www.socicos.com/js/map-script.js"></script>

<!--Scroll to top-->
<div class="scroll-to-top scroll-to-target" data-target="html"><span class="icon fa fa-angle-double-up"></span></div>


</body>
</html>