<!DOCTYPE html>
<html>
<?php echo $this->getLayout()->createBlock('core/template')->setTemplate('catalog/product/head.phtml')->toHtml(); ?>
<body>
<header class="main-header header-style-five">

    <!-- Header Top -->
    <?php echo $this->getLayout()->createBlock('core/template')->setTemplate('catalog/product/header_top.phtml')->toHtml(); ?>
    </div>
    <!-- Header Top End -->

    <!-- Main Box -->
    <div class="main-box">
        <div class="auto-container">
            <div class="outer-container clearfix">
                <!--Logo Box-->
                <?php echo $this->getLayout()->createBlock('core/template')->setTemplate('catalog/product/logo.phtml')->toHtml(); ?>
                <!--Nav Outer-->
                <div class="nav-outer clearfix">

                    <!-- Main Menu -->
                    <nav class="main-menu">
                        <div class="navbar-header">
                            <!-- Toggle Button -->
                            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>
                        </div>

                        <div class="navbar-collapse collapse clearfix">
                            <?php echo $this->getLayout()->createBlock('core/template')->setTemplate('catalog/product/top_navigation1.phtml')->toHtml(); ?>
                        </div>
                    </nav>
                    <!-- Main Menu End-->
                </div>
                <!--Nav Outer End-->

            </div>
        </div>
    </div>

    <!--Sticky Header-->
    <div class="sticky-header">
        <div class="auto-container">

            <div class="outer-container clearfix">
                <!--Logo Box-->
                <div class="logo-box pull-left">
                    <div class="logo"><a href="https://www.socicos.com/Home"><img src="https://www.socicos.com/images/logo-small.png" alt=""></a></div>
                </div>

                <!--Nav Outer-->
                <div class="nav-outer clearfix">
                    <!-- Main Menu -->
                    <nav class="main-menu">
                        <div class="navbar-header">
                            <!-- Toggle Button -->
                            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </button>
                        </div>

                        <div class="navbar-collapse collapse clearfix">
                            <?php echo $this->getLayout()->createBlock('core/template')->setTemplate('catalog/product/top_navigation2.phtml')->toHtml(); ?>
                        </div>
                    </nav>
                    <!-- Main Menu End-->

                </div>
                <!--Nav Outer End-->

            </div>

        </div>
    </div>
    <!--End Sticky Header-->

</header>
<!--End Main Header --><style>
    table {
        font-family: arial, sans-serif;
        border-collapse: collapse;
        width: 80%;
    }

    td, th {
        border: 1px solid #dddddd;
        text-align: left;
        padding: 8px;
    }
</style>

<!--Page Title-->
<section class="page-title" style="background-image:url(images/background/pattern-4.png);">
    <div class="auto-container">
        <h1>MOBILE WEB MARKETING </h1>
    </div>
    <!--Page Info-->
    <div class="page-info">
        <div class="auto-container">
            <div class="inner-container">
                <ul class="bread-crumb">
                    <li><a href="https://www.socicos.com/Home">Home</a></li>
                    <li>MOBILE WEB MARKETING </li>
                </ul>
            </div>
        </div>
    </div>
    <!--End Page Info-->
</section>


<div class="sidebar-page-container">
    <div class="auto-container">
        <div class="row clearfix">

            <!--Content Side-->
            <div class="content-side col-lg-8 col-md-8 col-sm-12 col-xs-12">
                <!--Our Single-->
                <div class="blog-single">
                    <div class="inner-box">
                        <div class="lower-content">
                            <h2 style="color: #0f1341"><b>MOBILE WEB MARKETING</b></h2><br>
                            <div class="text">
                                <table style="color: black">
                                    <tr>
                                        <td>1</td>
                                        <td>Behaviour of a Mobile User</td>
                                    </tr>
                                    <tr>
                                        <td>2</td>
                                        <td>Mobile Responsive Websites  </td>
                                    </tr>
                                    <tr>
                                        <td>3</td>
                                        <td>How to Create an Application?</td>
                                    </tr>
                                    <tr>
                                        <td>4</td>
                                        <td>Mobile Advertising</td>
                                    </tr>
                                    <tr>
                                        <td>5</td>
                                        <td>Mobile Analytics /td>
                                    </tr>
                                    <tr>
                                        <td>6</td>
                                        <td>SMS Marketing</td>
                                    </tr>
                                </table><br>
                                <h3>Behaviour of a Mobile User -</h3>
                                <p class="text-left">●	People on Mobile are very distracted or they display a distracted form of behaviour meaning the average attention span of a user on Mobile is very low. REASON : Notifications => Multitasking => Distraction<br>
                                    ●	Maximum Time - 10 Seconds<br>
                                    ●	Compact and Direct in Mobile Landing Pages/Webpage<br>
                                    ●	People have resistance towards filling web forms on mobile phones. REASON : People tend to get irritated while filling up web forms because the keyword hides the half screen and they also have a little difficulty in typing in Mobile<br>
                                    ●	People are more Call Friendly on Mobile Phone, hence clickable phone numbers becomes an extremely important part of Mobile Landing Pages<br><br>
                                    How to make a Phone Number clickable?<br>
                                    -	We need to create a link but a little different<br>
                                    &lt;a href =”tel:9632621778”> 9632621778&lt;/a&gt;
                                </p>
                                <h3>Mobile Responsive Websites v/s Dedicated Mobile Websites -</h3>
                                <p class="text-left">Same website works for Mobile as well<br>
                                    -	Responsive theme or Responsive Coding<br>
                                    -	If non-responsive theme in wordpress then use plugin WpTap<br>
                                    -	Wptouch<br>
                                    -	Non Wordpress Website can use Mofuse or duda.co if not responsive to create a Mobile Responsive version<br><br>

                                    Dedicated Websites like http://m.socicos.com and design short pages for it and then with the help of a coder we would have a redirect in tandem with the Screen Size of the Visitor.
                                </p>
                                <p class="text-left">Normally, it is done via .htaccess file (Coders know this, and can be found in Cpanel => File Manager, make sure you check mark show hidden files)</p>
                                <p class="text-left"> And then we can apply a rule there, if Screen <  (Width * Height) px ,  then redirect to
                                    http://m.socicos.com</p>
                                <p class="text-left">For getting http://m.socicos.com use a sub-domain to create one in cpanel.</p>
                                <h3>How to Create an Application?</h3>
                                <p class="text-left">Question - If you are a start-up then what is an efficient option, a mobile website or a mobile Application?<br><br>
                                    Answer - App in the beginning is not a good idea and the reason for it is that there is a lot of expenditure on Mobile Applications<br>
                                    1.	We have to develop the app, let’s say we make a good by spending 1,00,000 rupees<br>
                                    2.	We would need 2 versions bare minimum, one an Android and second an ios so this becomes 2 * 1,00,000 = Rs 2,00,000<br>
                                    3.	App Downloads - 10,000 downloads in a local city averaging at Rs 35 per Install leading to 3,50,000 INR<br>
                                    4.	On an Average a user would have 10-15 application on their phone, but peeps don’t use all 10 everyday or rather they don’t use some apps at all so we would need to run Re - Engagement Ads to these inactive installers because if they don’t use my app then there is no benefit to the business. So we need to run engagement ads showcasing new features, discount coupons and other luring things to get the user back to use our application! Again advertising cost and expenditure.! You can also use push notifications to re-engage the user!<br>
                                </p>
                                <p class="text-left">Upload it to the iOS store or Google Playstore<br>

                                    1.	You need to register as a developer with Apple (https://developer.apple.com)  or Google (https://play.google.com/apps/publish/signup/)<br>
                                    2.	For Apple - developer registration fee is 100$ per year and for Google Playstore there is one time fee of 25$<br>
                                    3.	Then you have to prepare your app graphics like banners promotional videos and any other graphic required<br>
                                    4.	Now you can submit your application for review, once reviewed you app would be live on iOS or Android Store<br>
                                </p>
                                <h3>MOBILE ADVERTISING - </h3>
                                <p class="text-left">●	InMobi (That’s the leader in Mobile advertising)<br>
                                    ●	Airpush (Minimum Deposit - 50 $)<br>
                                    ●	Google Adwords (From Google)<br>
                                </p>
                                <h3>MOBILE ANALYTICS -</h3>
                                <p class="text-left">1.	Go to your analytics account<br>
                                    2.	Add a Segment called Mobile Traffic (It would pre exist in segment list)<br>
                                    3.	Now browse entire analytics for mobile traffic analysis.<br>
                                </p>

                               </div>
                            <!--Two Column-->


                            <!--Accordian Boxed-->


                        </div>
                    </div>
                </div>
            </div>

            <!--Sidebar Side-->
            <div class="sidebar-side col-lg-4 col-md-4 col-sm-12 col-xs-12">
                <aside class="sidebar default-sidebar with-border">
                    <!-- Search -->
                    <!--Blog Category Widget-->
                    <!--Recent Comments-->
                    <div class="sidebar-widget recent-comments" style="left: 120px;">
                        <div class="sidebar-title" style="left: 37px;">
                            <h2>Resources</h2>
                        </div>
                        <?php echo $this->getLayout()->createBlock('core/template')->setTemplate('catalog/product/tools_resources.phtml')->toHtml(); ?>
                    </div>
                    <!-- Popular Posts -->
                    <!-- Popular Tags -->
                </aside>
            </div>

        </div>
    </div>
</div></section>
<!--End Partners Section-->

<!--Main Footer-->
<footer class="main-footer">
    <div class="auto-container">

        <!--Widgets Section-->
        <div class="widgets-section">
            <div class="row clearfix">

                <!--Column-->
                <div class="column col-md-4 col-sm-6 col-xs-12">
                    <div class="footer-widget links-widget">
                        <div class="footer-title">
                            <h2>Usefull Links</h2>
                        </div>
                        <div class="widget-content">
                            <div class="row clearfix">
                                <div class="widget-column col-md-6 col-sm-6 col-xs-12">
                                    <ul class="footer-list">
                                        <li><a href="https://www.socicos.com/Home">Home</a></li>
                                        <li><a href="https://www.socicos.com/Aboutus">About Us</a></li>
                                        <li><a href="https://www.socicos.com/Tools">Tools</a></li>
                                        <li><a href="https://www.socicos.com/Howitworks">How it Works?</a></li>
                                        <li><a href="https://www.socicos.com/Management">Resources</a></li>
                                        <li><a href="https://www.socicos.com/Contactus">Contact Us</a></li>
                                    </ul>
                                </div>
                                <div class="widget-column col-md-6 col-sm-6 col-xs-12">
                                    <ul class="footer-list">
                                        <li><a target="_blank" href="http://app.socicos.com/">Login</a></li>
                                        <li><a target="_blank" href="http://app.socicos.com/Socialregistration">Register</a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <!--Column-->
                <div class="column col-md-4 col-sm-6 col-xs-12">
                    <div class="footer-widget subscribe-widget">
                        <div class="footer-title">
                            <h2>Subscribe Us</h2>
                        </div>
                        <div class="widget-content">
                            <div class="text">Subscribe us for recieve latest Updates <br> News and Offers.</div>
                            <div class="subscribe-form">
                                <form method="post" action="contact.html">
                                    <div class="form-group">
                                        <input type="email" name="email" value="" placeholder="Email Address..." required="">
                                        <button type="submit" class="theme-btn"><span class="flaticon-right-arrow-1"></span></button>
                                    </div>
                                </form>
                            </div>
                            <ul class="social-icon-one">
                                <li><a href="#"><span class="fa fa-facebook-f"></span></a></li>
                                <li><a href="#"><span class="fa fa-twitter"></span></a></li>
                                <li><a href="#"><span class="fa fa-linkedin"></span></a></li>
                                <li><a href="#"><span class="fa fa-rss"></span></a></li>
                                <li><a href="#"><span class="fa fa-google-plus"></span></a></li>
                                <li><a href="#"><span class="fa fa-vimeo"></span></a></li>
                            </ul>
                        </div>
                    </div>
                </div>

                <!--Column-->
                <div class="column col-md-4 col-sm-6 col-xs-12">
                    <div class="footer-widget office-widget">
                        <div class="footer-title">
                            <h2>Corporate Office</h2>
                        </div>
                        <div class="widget-content">
                            <div class="single-item-carousel owl-carousel owl-theme">

                                <div class="office-info">
                                    <ul>
                                        <li><strong>Address:</strong></li>
                                        <li>3rd Floor, SuryaPrema
                                            #15, Plot No 1 & 2, 1st Cross, Manjunathanagar, Kanakpura Road, Bengaluru, Karnataka 560062</li>
                                        <li><a href="#">Find Us On Map</a></li>
                                    </ul>
                                </div>

                                <div class="office-info">
                                    <ul>
                                        <li><strong>Address:</strong></li>
                                        <li>3rd Floor, SuryaPrema
                                            #15, Plot No 1 & 2, 1st Cross, Manjunathanagar, Kanakpura Road, Bengaluru, Karnataka 560062 </li>
                                        <li><a href="#">Find Us On Map</a></li>
                                    </ul>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>

    </div>
    <!--Copyright-->
    <div class="copyright">Copyright &copy; 2012-2018 The SOCICOS. All rights reserved.</div>
</footer>
<!--Main Footer-->
<!--Bottom Parallax-->

</div>
<!--End pagewrapper-->

<!--Scroll to top-->
<div class="scroll-to-top scroll-to-target" data-target="html"><span class="icon fa fa-angle-double-up"></span></div>

<script src="https://www.socicos.com/js/jquery.js"></script>
<!--Revolution Slider-->
<script src="https://www.socicos.com/assets/revolution/js/jquery.themepunch.revolution.min.js"></script>
<script src="https://www.socicos.com/assets/revolution/js/jquery.themepunch.tools.min.js"></script>
<script src="https://www.socicos.com/assets/revolution/js/extensions/revolution.extension.actions.min.js"></script>
<script src="https://www.socicos.com/assets/revolution/js/extensions/revolution.extension.carousel.min.js"></script>
<script src="https://www.socicos.com/assets/revolution/js/extensions/revolution.extension.kenburn.min.js"></script>
<script src="https://www.socicos.com/assets/revolution/js/extensions/revolution.extension.layeranimation.min.js"></script>
<script src="https://www.socicos.com/assets/revolution/js/extensions/revolution.extension.migration.min.js"></script>
<script src="https://www.socicos.com/assets/revolution/js/extensions/revolution.extension.navigation.min.js"></script>
<script src="https://www.socicos.com/assets/revolution/js/extensions/revolution.extension.parallax.min.js"></script>
<script src="https://www.socicos.com/assets/revolution/js/extensions/revolution.extension.slideanims.min.js"></script>
<script src="https://www.socicos.com/assets/revolution/js/extensions/revolution.extension.video.min.js"></script>
<script src="https://www.socicos.com/js/main-slider-script.js"></script>

<script src="https://www.socicos.com/js/jquery.js"></script>
<script src="https://www.socicos.com/js/bootstrap.min.js"></script>
<script src="https://www.socicos.com/js/jquery.fancybox.pack.js"></script>
<script src="https://www.socicos.com/js/jquery.fancybox-media.js"></script>
<script src="https://www.socicos.com/js/owl.js"></script>
<script src="https://www.socicos.com/js/wow.js"></script>
<script src="https://www.socicos.com/js/validate.js"></script>
<script src="https://www.socicos.com/js/jquery-ui.js"></script>
<script src="https://www.socicos.com/js/knob.js"></script>
<script src="https://www.socicos.com/js/slick.js"></script>
<script src="https://www.socicos.com/js/appear.js"></script>
<script src="https://www.socicos.com/js/script.js"></script>
<!--<script src="https://www.socicos.com/js/validate.js"></script>-->
<script src="http://maps.google.com/maps/api/js?key=AIzaSyBKS14AnP3HCIVlUpPKtGp7CbYuMtcXE2o"></script>
<script src="https://www.socicos.com/js/map-script.js"></script>

<!--Scroll to top-->
<div class="scroll-to-top scroll-to-target" data-target="html"><span class="icon fa fa-angle-double-up"></span></div>


</body>
</html>