<?php $path = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB, true) . 'socicos/'; ?>
<section class="partners-section">
    <div class="auto-container">
        <div class="row clearfix">

            <!--Title Column-->
            <div class="title-column col-md-4 col-sm-12 col-xs-12">
                <div class="inner-column">
                    <h2>Our Partners</h2>
                    <div class="text">Our strategic alliance formulates a WIN-WIN strategy for all partners involved.</div>
                    <a target="_blank" href="<?php echo Mage::getUrl('customer/account/create'); ?>" class="theme-btn btn-style-one">Join With Us</a>
                </div>
            </div>

            <!--Partners Column-->
            <div class="partners-column col-md-8 col-sm-12 col-xs-12">
                <div class="row clearfix">
                    <!--Column-->
                    <div class="column col-md-6 col-sm-6 col-xs-12">
                        <div class="partner-block">
                            <div class="inner-box">
                                <div class="client-img">
                                    <img src="<?php echo $path; ?>images/yoneak.png" alt="" />
                                </div>
                                <div class="text">At Yoneak Services Pvt. Ltd. We bring you best deals available direct from merchant stores.</div>
                                <a class="read-more" target="_blank" href="http://www.yoneak.com/"><span class="icon flaticon-right-arrow-1"></span> Visit Website</a>
                            </div>
                        </div>
                    </div>
                    <!--Column-->
                    <div class="column col-md-6 col-sm-6 col-xs-12">
                        <div class="partner-block">
                            <div class="inner-box">
                                <div class="client-img">
                                    <img src="<?php echo $path; ?>images/arixlelogo1.png" alt="" />
                                </div>
                                <div class="text">We are Arixle Solutions, an IT consulting and software outsourcing company known for our deep industry experience and high customer satisfaction. </div>
                                <a class="read-more" href="http://arixle.com/"><span class="icon flaticon-right-arrow-1"></span> Visit Website</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
