<?php $path = Mage::getBaseUrl( Mage_Core_Model_Store::URL_TYPE_WEB, true ) . 'socicos/'; ?>
<ul class="blog-cat-two">
    <li><a href="<?php echo Mage::getBaseUrl(); ?>socialmediamanagement">SOCIAL MEDIA MANAGEMENT</a></li>
    <li><a href="<?php echo Mage::getBaseUrl(); ?>leadgeneration">LEAD GENERATION</a></li>
    <li><a href="<?php echo Mage::getBaseUrl(); ?>mobilemarketing">MOBILE WEB MARKETING</a></li>
    <li><a href="<?php echo Mage::getBaseUrl(); ?>websitedesigndevelopement">WEBSITE DESIGN & DEVELOPMENT</a></li>
    <li><a href="<?php echo Mage::getBaseUrl(); ?>tasktracking">TASK TRACKING & REMINDERS</a></li>
    <li><a href="<?php echo Mage::getBaseUrl(); ?>smsmarketing">SMS MARKETING</a></li>
    <li><a href="<?php echo Mage::getBaseUrl(); ?>affiliatemarketing">AFFILIATE MARKETING</a></li>
    <li><a href="<?php echo Mage::getBaseUrl(); ?>digitalmarketing">DIGITAL MARKETING TOOLS</a></li>
</ul>