<?php $path = Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_WEB, true) . 'socicos/'; ?>
<ul class="navigation clearfix">
    <li><a href="<?php echo Mage::getBaseUrl(); ?>">Home</a></li>
    <li><a href="<?php echo Mage::getBaseUrl(); ?>about-us">About Us</a></li>
    <li><a href="<?php echo Mage::getBaseUrl(); ?>tools">Tools</a></li>
    <li><a href="<?php echo Mage::getBaseUrl(); ?>howitworks">How it Works?</a></li>
    <li><a href="<?php echo Mage::getBaseUrl(); ?>management">Resources</a></li>
    <li><a href="<?php echo Mage::getBaseUrl(); ?>contactus">Contact Us</a></li>
</ul>