<!DOCTYPE html>
<html>
    <?php echo $this->getLayout()->createBlock('core/template')->setTemplate('catalog/product/head.phtml')->toHtml(); ?>
    <body>
        <header class="main-header header-style-five">

            <!-- Header Top -->
            <?php echo $this->getLayout()->createBlock('core/template')->setTemplate('catalog/product/header_top.phtml')->toHtml(); ?>
        </div>
        <!-- Header Top End -->

        <!-- Main Box -->
        <div class="main-box">
            <div class="auto-container">
                <div class="outer-container clearfix">
                    <!--Logo Box-->
                    <?php echo $this->getLayout()->createBlock('core/template')->setTemplate('catalog/product/logo.phtml')->toHtml(); ?>
                    <!--Nav Outer-->
                    <div class="nav-outer clearfix">

                        <!-- Main Menu -->
                        <nav class="main-menu">
                            <div class="navbar-header">
                                <!-- Toggle Button -->
                                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                </button>
                            </div>

                            <div class="navbar-collapse collapse clearfix">
                                <?php echo $this->getLayout()->createBlock('core/template')->setTemplate('catalog/product/top_navigation1.phtml')->toHtml(); ?>
                            </div>
                        </nav>
                        <!-- Main Menu End-->
                    </div>
                    <!--Nav Outer End-->

                </div>
            </div>
        </div>

        <!--Sticky Header-->
        <div class="sticky-header">
            <div class="auto-container">

                <div class="outer-container clearfix">
                    <!--Logo Box-->
                    <div class="logo-box pull-left">
                        <div class="logo"><a href="https://www.socicos.com/Home"><img src="https://www.socicos.com/images/logo-small.png" alt=""></a></div>
                    </div>

                    <!--Nav Outer-->
                    <div class="nav-outer clearfix">
                        <!-- Main Menu -->
                        <nav class="main-menu">
                            <div class="navbar-header">
                                <!-- Toggle Button -->
                                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                    <span class="icon-bar"></span>
                                </button>
                            </div>

                            <div class="navbar-collapse collapse clearfix">
                                <?php echo $this->getLayout()->createBlock('core/template')->setTemplate('catalog/product/top_navigation2.phtml')->toHtml(); ?>
                            </div>
                        </nav>
                        <!-- Main Menu End-->

                    </div>
                    <!--Nav Outer End-->

                </div>

            </div>
        </div>
        <!--End Sticky Header-->

    </header>
    <!--End Main Header --><section class="page-title" style="background-image:url(images/background/pattern-4.png);">
        <div class="auto-container">
            <h1>WEBSITE DESIGN & DEVELOPMENT</h1>
        </div>
        <!--Page Info-->
        <div class="page-info">
            <div class="auto-container">
                <div class="inner-container">
                    <ul class="bread-crumb">
                        <li><a href="https://www.socicos.com/Home">Home</a></li>
                        <li>WEBSITE DESIGN & DEVELOPMENT</li>
                    </ul>
                </div>
            </div>
        </div>
        <!--End Page Info-->
    </section>

    <div class="sidebar-page-container">
        <div class="auto-container">
            <div class="row clearfix">

                <!--Content Side-->
                <div class="content-side col-lg-8 col-md-8 col-sm-12 col-xs-12">
                    <!--Our Single-->
                    <div class="blog-single">
                        <div class="inner-box">
                            <h2 style="color: #0f1341"><b>WEBSITE DESIGN & DEVELOPMENT</b></h2><br>

                            <div class="lower-content">
                                <div class="text">
                                    <h3>Website Planning</h3>
                                    <p class="text-left">The address of any website or webpage is known as URL (Uniform Resource Locator).</p>
                                    <p class="text-left"><strong>URL consists of three components:</strong><br>
                                        1.	Sub domain<br>
                                        2.	Domain Name<br>
                                        3.	Extension<br>
                                        Like: subdomain.domain name. Extension
                                    </p>
                                    <p class="text-left"><strong>Sub Domain:</strong> It is the first part of the URL and by default it is www (World Wide Web).</p>
                                    <p class="text-left">Many (Unlimited) sub domains can be created under one domain.</p>
                                    <p class="text-left">E.g.     blog.socicos.com or support.socicos.com<br>
                                        Seller.snapdeal.com or sellers.flipkart.com<br>
                                    </p>
                                    <p class="text-left">Sub domain creation is free under any domain.</p>
                                    <p class="text-left"><strong>Use of sub domain –</strong> To divert the traffic to different servers as one server cannot handle the whole traffic. When there is huge traffic on you website.</p>
                                    <p class="text-left"><strong>Domain:</strong>It is the main part of URL, which you select and it reflects your business.<br>
                                        Domain name should be easy to remember, spell and write.
                                    </p>
                                    <p class="text-left"><strong>Extension :</strong>:  It is the end part of URL. Mostly .com is used and it is commercial worldwide.<br>
                                        There are more than 5000 extensions.<br>
                                        Like: .co. in – Commercial in INDIA<br>
                                        .co.uk – Commercial in UK<br>
                                        In US the basic extension is .com. In India the basic is .in<br>
                                    </p>
                                    <p class="text-left">
                                        Few Keys Points:
                                    </p>
                                    <p class="text-left"><strong>Web</strong>a part of internet which is open to all. </p>
                                    <p class="text-left"><strong>Web Browser: </strong>They are software to search a piece of information from web. </p>
                                    <p class="text-left"><strong>Web Server: </strong>It is storage which can be fetched from an URL or IP.</p>
                                    <p class="text-left"><strong>Web Hosting: </strong>It is the method to host your website on web server so that user can fetch the information in it using a web browser from an URL or IP in any part of world.</p>
                                    <h3>Types of Websites</h3>
                                    <p class="text-left">Websites can be divided in two types on the basis of:</p>
                                    <p class="text-left">1.	Purpose – What is the purpose of any website<br>
                                        a)	Personal – Created for himself – where the creator can showcase himself and his work.<br>
                                        b)	Business<br>
                                        c)	E commerce<br>
                                        d)	Social Network<br>
                                        e)	Informational<br>
                                        I.	Blog – Created to share a piece of information in any niche.<br>
                                        II.	Forum – For Discussions on certain topics. E.g.  www.team-php.com/forum<br>
                                        III.Portal – Websites like indiamart.com, naukari.com, cartrade.com, olx.com<br>
                                        IV.	Wikipedia<br>
                                        V.	Answering Websites – For example Quora<br>
                                        VI.	Web directories – Yellow Pages<br>
                                    </p>
                                    <p class="text-left">2.	Functionality – What is the functional structure of any website.<br>
                                        a)	Static: The websites in which to make a change, a change is need to be done in code, webhosting. The code needs to be withdrawn from hosting to do the required changes and after it needs to be re upload.<br>
                                        b)	Dynamic: The websites in which a change can be made without changing the code.<br>
                                        •	Even a user can change the webpage through comment, like and it goes live simultaneously.<br>
                                        •	Even the password is not required to make a change. Example- Facebook, twitter etc.<br>
                                        •	Or the creator/owner has a CMS (content management system) to make changes in it.<br>
                                        c)	Responsive: The website which adjust itself according to the digital device in tandem to the view port area.<br>
                                        d)	Mobile Dedicated website. The websites dedicatedly created for mobile with “m” as a sub domain.  Like: m.domainname.com<br>
                                    </p>
                                    <h3>Website Planning</h3>
                                    <p class="text-left">Steps of website planning:</p>
                                    <p class="text-left">1.	Identify your primary and secondary objectives.<br>
                                        2.	Plan the number of web pages in our website<br>
                                        3.	Create a blue print of each and every webpage/structure/layout.<br>
                                        4.	Do some A/B testing<br>
                                        5.	Measure the performance of your WebPages and do necessary changes.<br>
                                    </p>

                                </div>
                                <!--Two Column-->


                                <!--Accordian Boxed-->


                            </div>
                        </div>
                    </div>
                </div>

                <!--Sidebar Side-->
                <div class="sidebar-side col-lg-4 col-md-4 col-sm-12 col-xs-12">
                    <aside class="sidebar default-sidebar with-border">
                        <!-- Search -->
                        <!--Blog Category Widget-->
                        <!--Recent Comments-->
                        <div class="sidebar-widget recent-comments" style="left: 120px;">
                            <div class="sidebar-title" style="left: 37px;">
                                <h2>Resources</h2>
                            </div>
                            <?php echo $this->getLayout()->createBlock('core/template')->setTemplate('catalog/product/tools_resources.phtml')->toHtml(); ?>
                        </div>
                        <!-- Popular Posts -->
                        <!-- Popular Tags -->
                    </aside>
                </div>

            </div>
        </div>
    </div></section>
<!--End Partners Section-->

<!--Main Footer-->
<footer class="main-footer">
    <div class="auto-container">

        <!--Widgets Section-->
        <div class="widgets-section">
            <div class="row clearfix">

                <!--Column-->
                <div class="column col-md-4 col-sm-6 col-xs-12">
                    <div class="footer-widget links-widget">
                        <div class="footer-title">
                            <h2>Usefull Links</h2>
                        </div>
                        <div class="widget-content">
                            <div class="row clearfix">
                                <div class="widget-column col-md-6 col-sm-6 col-xs-12">
                                    <ul class="footer-list">
                                        <li><a href="https://www.socicos.com/Home">Home</a></li>
                                        <li><a href="https://www.socicos.com/Aboutus">About Us</a></li>
                                        <li><a href="https://www.socicos.com/Tools">Tools</a></li>
                                        <li><a href="https://www.socicos.com/Howitworks">How it Works?</a></li>
                                        <li><a href="https://www.socicos.com/Management">Resources</a></li>
                                        <li><a href="https://www.socicos.com/Contactus">Contact Us</a></li>
                                    </ul>
                                </div>
                                <div class="widget-column col-md-6 col-sm-6 col-xs-12">
                                    <ul class="footer-list">
                                        <li><a target="_blank" href="http://app.socicos.com/">Login</a></li>
                                        <li><a target="_blank" href="http://app.socicos.com/Socialregistration">Register</a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <!--Column-->
                <div class="column col-md-4 col-sm-6 col-xs-12">
                    <div class="footer-widget subscribe-widget">
                        <div class="footer-title">
                            <h2>Subscribe Us</h2>
                        </div>
                        <div class="widget-content">
                            <div class="text">Subscribe us for recieve latest Updates <br> News and Offers.</div>
                            <div class="subscribe-form">
                                <form method="post" action="contact.html">
                                    <div class="form-group">
                                        <input type="email" name="email" value="" placeholder="Email Address..." required="">
                                        <button type="submit" class="theme-btn"><span class="flaticon-right-arrow-1"></span></button>
                                    </div>
                                </form>
                            </div>
                            <ul class="social-icon-one">
                                <li><a href="#"><span class="fa fa-facebook-f"></span></a></li>
                                <li><a href="#"><span class="fa fa-twitter"></span></a></li>
                                <li><a href="#"><span class="fa fa-linkedin"></span></a></li>
                                <li><a href="#"><span class="fa fa-rss"></span></a></li>
                                <li><a href="#"><span class="fa fa-google-plus"></span></a></li>
                                <li><a href="#"><span class="fa fa-vimeo"></span></a></li>
                            </ul>
                        </div>
                    </div>
                </div>

                <!--Column-->
                <div class="column col-md-4 col-sm-6 col-xs-12">
                    <div class="footer-widget office-widget">
                        <div class="footer-title">
                            <h2>Corporate Office</h2>
                        </div>
                        <div class="widget-content">
                            <div class="single-item-carousel owl-carousel owl-theme">

                                <div class="office-info">
                                    <ul>
                                        <li><strong>Address:</strong></li>
                                        <li>3rd Floor, SuryaPrema
                                            #15, Plot No 1 & 2, 1st Cross, Manjunathanagar, Kanakpura Road, Bengaluru, Karnataka 560062</li>
                                        <li><a href="#">Find Us On Map</a></li>
                                    </ul>
                                </div>

                                <div class="office-info">
                                    <ul>
                                        <li><strong>Address:</strong></li>
                                        <li>3rd Floor, SuryaPrema
                                            #15, Plot No 1 & 2, 1st Cross, Manjunathanagar, Kanakpura Road, Bengaluru, Karnataka 560062 </li>
                                        <li><a href="#">Find Us On Map</a></li>
                                    </ul>
                                </div>

                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>

    </div>
    <!--Copyright-->
    <div class="copyright">Copyright &copy; 2012-2018 The SOCICOS. All rights reserved.</div>
</footer>
<!--Main Footer-->
<!--Bottom Parallax-->

</div>
<!--End pagewrapper-->

<!--Scroll to top-->
<div class="scroll-to-top scroll-to-target" data-target="html"><span class="icon fa fa-angle-double-up"></span></div>

<script src="https://www.socicos.com/js/jquery.js"></script>
<!--Revolution Slider-->
<script src="https://www.socicos.com/assets/revolution/js/jquery.themepunch.revolution.min.js"></script>
<script src="https://www.socicos.com/assets/revolution/js/jquery.themepunch.tools.min.js"></script>
<script src="https://www.socicos.com/assets/revolution/js/extensions/revolution.extension.actions.min.js"></script>
<script src="https://www.socicos.com/assets/revolution/js/extensions/revolution.extension.carousel.min.js"></script>
<script src="https://www.socicos.com/assets/revolution/js/extensions/revolution.extension.kenburn.min.js"></script>
<script src="https://www.socicos.com/assets/revolution/js/extensions/revolution.extension.layeranimation.min.js"></script>
<script src="https://www.socicos.com/assets/revolution/js/extensions/revolution.extension.migration.min.js"></script>
<script src="https://www.socicos.com/assets/revolution/js/extensions/revolution.extension.navigation.min.js"></script>
<script src="https://www.socicos.com/assets/revolution/js/extensions/revolution.extension.parallax.min.js"></script>
<script src="https://www.socicos.com/assets/revolution/js/extensions/revolution.extension.slideanims.min.js"></script>
<script src="https://www.socicos.com/assets/revolution/js/extensions/revolution.extension.video.min.js"></script>
<script src="https://www.socicos.com/js/main-slider-script.js"></script>

<script src="https://www.socicos.com/js/jquery.js"></script>
<script src="https://www.socicos.com/js/bootstrap.min.js"></script>
<script src="https://www.socicos.com/js/jquery.fancybox.pack.js"></script>
<script src="https://www.socicos.com/js/jquery.fancybox-media.js"></script>
<script src="https://www.socicos.com/js/owl.js"></script>
<script src="https://www.socicos.com/js/wow.js"></script>
<script src="https://www.socicos.com/js/validate.js"></script>
<script src="https://www.socicos.com/js/jquery-ui.js"></script>
<script src="https://www.socicos.com/js/knob.js"></script>
<script src="https://www.socicos.com/js/slick.js"></script>
<script src="https://www.socicos.com/js/appear.js"></script>
<script src="https://www.socicos.com/js/script.js"></script>
<!--<script src="https://www.socicos.com/js/validate.js"></script>-->
<script src="http://maps.google.com/maps/api/js?key=AIzaSyBKS14AnP3HCIVlUpPKtGp7CbYuMtcXE2o"></script>
<script src="https://www.socicos.com/js/map-script.js"></script>

<!--Scroll to top-->
<div class="scroll-to-top scroll-to-target" data-target="html"><span class="icon fa fa-angle-double-up"></span></div>


</body>
</html>