<?php
$pageSize = 50;
$currPage = 1;
if (isset($_REQUEST['limit'])) {
    $pageSize = $_REQUEST['limit'];
}

if (isset($_REQUEST['p'])) {
    $currPage = $_REQUEST['p'];
}

$helper = Mage::helper('keywordmanager/data');
$customerId = $helper->getCurrentCustomer();
$websiteAuditCollection = Mage::getModel('linkanalysis/linkanalysis')
        ->getCollection()
        /*->addFieldToFilter('status', '1')*/
        ->addFieldToFilter('customer_id', $customerId)
        ->setOrder('linkanalysis_id', 'DESC');
$recordsCount = $websiteAuditCollection->getSize();
$websiteAuditCollection->setPageSize($pageSize)->setCurPage($currPage);
?>

<div class="page-title">
    <div class="row">
        <div class="col-sm-6">
            <h4 class="mb-0"> Welcome to Website Audit</h4>
        </div>
        <div class="col-sm-6">
            <ol class="breadcrumb pt-0 pr-0 float-left float-sm-right">
                <li class="breadcrumb-item"><a href="<?php echo Mage::getBaseUrl(); ?>" class="default-color">Home</a></li>
                <li class="breadcrumb-item active">Website Audit</li>
            </ol>
        </div>
    </div>
</div>

<div class="row" style="margin-bottom: -30px;">
    <div class="col-xl-12 mb-30" id="msg">

    </div>
</div>

<div class="row" style="margin-bottom: -50px;">
    <div class="col-xl-12 mb-30">
        <div class="card card-statistics mb-30">
            <div class="card-body">
                <h5 class="card-title">Add Your Website URL</h5>
                <form id="addKeywordFrm">
                    <div class="row">
                        <div class="col-xl-3 mb-30" style="margin-bottom: .5rem !important; padding-right:0;">
                            <div class="form-group">
                                <input type="text" class="form-control" id="websiteURL" aria-describedby="websiteURL" placeholder="Enter Website URL" required="required">
                                <small id="websiteURL" class="form-text text-muted">Please enter your website URL.</small>
                            </div>
                        </div>
                        <div class="col-xl-2 mb-30" style="margin-bottom: .5rem !important; padding-left:0;">
                            <div class="form-group">
                                <input type="submit" id="btnSubmit" style="display: none;">
                                <button onclick="addUrl();" type="button" class="btn btn-primary" style="width: 100%; border:  solid 2px #ccc; height: 45px;">Add Website URL</button>
                                <small id="emailHelp" class="form-text text-muted">&nbsp;</small>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

<div class="row" id="urlContainer">   
    <div class="col-xl-12 mb-30">     
        <div class="card card-statistics h-100"> 
            <div class="card-body">
                <div class="d-block d-md-flex justify-content-between">
                    <div class="d-block">
                        <h5 class="card-title pb-0 border-0" style="padding: 15px;margin-bottom: 0;">Manage Your Keyword</h5>
                    </div>
                    <!--<div class="d-block d-md-flex clearfix sm-mt-20">
                        <div class="clearfix">
                            <div class="box">
                                <select class="fancyselect sm-mb-20 mr-20" style="display: none;">
                                    <option value="50">50</option>
                                    <option value="100">100</option>
                                    <option value="200">200</option>
                                    <option value="500">500</option>
                                </select>
                                <div class="nice-select fancyselect sm-mb-20 mr-20" tabindex="0">
                                    <ul class="list">
                                        <li data-value="10" class="option selected">10</li>
                                        <li data-value="20" class="option">20</li>
                                        <li data-value="50" class="option">50</li>
                                        <li data-value="100" class="option">100</li>
                                    </ul>
                                </div>
                            </div>
                        </div>
                        <div class="widget-search ml-0 clearfix">
                            <i class="fa fa-search"></i>
                            <input type="search" class="form-control" placeholder="Search....">
                        </div>
                    </div>-->
                </div>
                <div class="table-responsive mt-15">
                    <table id="datatable-website-audit" class="table table-bordered table-striped center-aligned-table mb-0">
                        <thead>
                            <tr class="text-dark">
                                <th style="text-align: center;">#</th>
                                <th>SL No</th>
                                <th>URL</th>
                                <th>Created At</th>
                                <th>Action</th>
                                <th></th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php if ($websiteAuditCollection->getSize() > 0): ?>
                                <?php $count = 1; ?>
                                <?php foreach ($websiteAuditCollection as $websiteAudit): ?>
                                    <tr>
                                        <td style="text-align: center;">
                                            <input style="margin-top: -9px;" value="<?php echo $websiteAudit->getId(); ?>" type="checkbox" class="form-check-input">
                                        </td>
                                        <td><?php echo $count; ?></td>
                                        <td><?php echo $websiteAudit->getUrl(); ?></td>
                                        <td><?php echo $websiteAudit->getCreatedAt(); ?></td>
                                        <?php /*?><td><a href="<?php echo $this->getUrl('website-audit-view') . '?uid=' . $websiteAudit->getId(); ?>" class="btn btn-outline-success btn-sm">View</a></td><?php */?>
                                        <td><a href="<?php echo Mage::getBaseUrl() . 'websiteaudit/index/viewwebsite?uid=' . $websiteAudit->getId(); ?>" class="btn btn-outline-success btn-sm">View</a></td>
                                        <td>
                                            <a href="javascript:deleteURL('<?php echo $websiteAudit->getId(); ?>');" class="btn btn-outline-success btn-sm">
                                                <i class="fa fa-trash-o" style="font-size:15px;"></i>
                                            </a>
                                        </td>
                                    </tr>
                                    <?php $count++; ?>
                                <?php endforeach; ?>
                            <?php else: ?>
                                <tr>
                                    <td colspan="7">
                                        Sorry! URL Found In Your Account.
                                    </td>
                                </tr>
                            <?php endif; ?>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>   
    </div>
</div>

<!--<div class="row">
    <div class="col-sm-12 col-md-5">
        <div class="dataTables_info" id="datatable_info" role="status" aria-live="polite">Showing <?php echo (($currPage-1)*$pageSize)+1;?> to <?php echo $pageSize; ?> of <?php echo $recordsCount; ?> entries</div>  
    </div>
    <div class="col-sm-12 col-md-7">
        <div class="dataTables_paginate paging_simple_numbers" id="datatable_paginate" style="float: right;">
            <ul class="pagination">
                <li class="paginate_button page-item previous disabled" id="datatable_previous">
                    <a href="#" aria-controls="datatable" data-dt-idx="0" tabindex="0" class="page-link">Previous</a>
                </li>
                <li class="paginate_button page-item active">
                    <a href="#" aria-controls="datatable" data-dt-idx="1" tabindex="0" class="page-link">1</a>
                </li>
                <li class="paginate_button page-item ">
                    <a href="#" aria-controls="datatable" data-dt-idx="2" tabindex="0" class="page-link">2</a>
                </li>
                <li class="paginate_button page-item ">
                    <a href="#" aria-controls="datatable" data-dt-idx="3" tabindex="0" class="page-link">3</a>
                </li>
                <li class="paginate_button page-item ">
                    <a href="#" aria-controls="datatable" data-dt-idx="4" tabindex="0" class="page-link">4</a>
                </li>
                <li class="paginate_button page-item ">
                    <a href="#" aria-controls="datatable" data-dt-idx="5" tabindex="0" class="page-link">5</a>
                </li>
                <li class="paginate_button page-item ">
                    <a href="#" aria-controls="datatable" data-dt-idx="6" tabindex="0" class="page-link">6</a>
                </li>
                <li class="paginate_button page-item next" id="datatable_next">
                    <a href="#" aria-controls="datatable" data-dt-idx="7" tabindex="0" class="page-link">Next</a>
                </li>
            </ul>
        </div>
    </div>
</div>-->

<script>
document.addEventListener("DOMContentLoaded", function(){
       jQuery('#datatable-website-audit').DataTable(); 
    });
    function addUrl() {
        var websiteURL = document.getElementById('websiteURL').value;
        var param = "websiteURL=" + websiteURL;
        if (websiteURL.length >= 3) {
            var url = "<?php echo Mage::getBaseUrl() . 'websiteaudit/index/saveWebsiteURL?'; ?>" + param;
            jQuery("#pre-loader").css("opacity", '0.8');
            jQuery("#pre-loader").show();
            jQuery.ajax({
                type: "POST",
                url: url,
                data: '',
                success: function (data)
                {
                    var objData = jQuery.parseJSON(data);
                    document.getElementById("msg").innerHTML = objData.msg;
                    if (parseInt(objData.status) >= 2) {
                        jQuery("#pre-loader").hide();
                        document.location.href = objData.url;
                    } else {
                        updatePage();
                    }
                }
            });
        } else {
            document.getElementById("btnSubmit").click();
        }
    }

    function updatePage() {
        var url = "<?php echo Mage::getBaseUrl() . 'websiteaudit/'; ?>";
        //jQuery("#pre-loader").css("opacity", '0.8');
        //jQuery("#pre-loader").show();
        jQuery.ajax({
            type: "POST",
            url: url,
            data: '',
            success: function (data)
            {
                var $result = jQuery(data).find('#urlContainer').html();
                jQuery("#urlContainer").html($result);
                jQuery("#pre-loader").hide();
            }
        });
    }

    function deleteURL(urlId) {
        var param = "urlId=" + urlId;
        var url = "<?php echo Mage::getBaseUrl() . 'websiteaudit/index/deleteWebsiteURL?'; ?>" + param;
        jQuery("#pre-loader").css("opacity", '0.8');
        jQuery("#pre-loader").show();
        jQuery.ajax({
            type: "POST",
            url: url,
            data: '',
            success: function (data)
            {
                var objData = jQuery.parseJSON(data);
                document.getElementById("msg").innerHTML = objData.msg;
                if (parseInt(objData.status) >= 2) {
                    jQuery("#pre-loader").hide();
                    document.location.href = objData.url;
                } else {
                    updatePage();
                }
            }
        });
    }
</script>